### ISSUE TITLE
Trouble running cudnn on Ubuntu 14.04

### ISSUE THREAD

**Issue by jan0e** [NVIDIA/nvidia-docker#109]
Hi,

I have trouble setting up a docker image with Ubuntu 14.04 as host, where torch is able to utilize cudnn5. Since it is working with Ubuntu 16.04 as host I do not think that there is a problem with torch. CUDA seems to work (e.g. cunn can be used). The machine configurations are as followed:

Working:
Host OS: Ubuntu 16.04
Card: GeForce GTX 970
Driver Version: 361.42
NVCC: V7.5.17

Not working:
Host OS: Ubuntu 14.04
Card: 4x GeForce GTX Titan
Driver Version: 352.63
NVCC: not installed

The image taken as baseline is `nvidia/cuda:7.5-cudnn5-devel-ubuntu14.04`. Since the goal is to create a docker image, which runs on a wide variety of machines the driver on the Ubuntu 14.04 machine was not updated (also [this table](https://github.com/NVIDIA/nvidia-docker/wiki/CUDA) states that the minimum requirement for cuda 7.5 is fulfilled). It is of course possible to do that, if you think that this is a reason why it might fail.

This is the [Dockerfile](https://gist.github.com/jan0e/3b6214a33097ad53ea34f28b0c3bb00b) used to create the image by running:
```
nvidia-docker build -t torch-test .
```
Running it like this on the Ubuntu 16.04 machine
```
nvidia-docker run -ti --rm torch-test /root/startTraining.sh
```
starts the training using cudnn as backend. Doing the same on the Ubuntu 14.04 machine is producing this error:
```
/opt/torch/install/share/lua/5.1/cudnn/init.lua:45: Error in CuDNN: CUDNN_STATUS_NOT_INITIALIZED
```
Running the image created on the Ubuntu 14.04 with Ubuntu 16.04 as host is working fine.

Can you spot any obvious reason why this is not working? Any hints on how to solve this issue are highly appreciated.

Many thanks,
jan0e

**Comment by flx42** [comment]
Weird, it looks like this issue:
https://groups.google.com/forum/#!searchin/caffe-users/caffe-users/N0DJy4OFy5I/MUvxJytUEgAJ
But I cannot reproduce this issue.

You have the same driver version (352.63) as the Caffe user, can you try upgrading to 352.93 or 361.XX like your first machine?

**Comment by ArtanisCV** [comment]
This may due to the wrong cuDNN in the docker image. You can try to downgrade the libcudnn: `apt-get install libcudnn5=5.0.5-1+cuda7.5`.

**Comment by flx42** [comment]
Right, that's likely, please do `docker pull` of the cudnn5 base image and try again.

**Comment by jan0e** [comment]
Thanks for the quick support. I upgraded the driver on my Ubuntu 14.04 to 361.45.11 and it is working now. I also checked the version number of my libcudnn and it is indeed the version bound to cuda 8.0 (as in the referenced issue). I will try to downgrade it and will perform a test on another machine with 14.04 to see if this also would resolve the issue.

**Comment by flx42** [comment]
Don't downgrade, just do a `docker pull nvidia/cuda:7.5-cudnn5-devel-ubuntu14.04` and rebuild your image.
