### ISSUE TITLE
"File has unexpected size" with nvidia/cuda:10.1-devel-ubuntu18.04

### ISSUE THREAD

**Issue by tgaddair** [NVIDIA/nvidia-docker#1141]
In [Horovod](https://github.com/horovod/horovod), we base some of our integration tests on `nvidia/cuda:10.1-devel-ubuntu18.04`, but since last night building our test image has been failing with the following error:

```
[91mE: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/./libnccl-dev_2.5.4-1+cuda10.1_amd64.deb  File has unexpected size (20038080 != 20039408). Mirror sync in progress? [IP: 192.229.211.70 443]
   Hashes of expected file:
    - SHA512:03699ded9985356a392a65f9273dd441ccded2c3a4c9bb58d212d1be7fbc30d8020a6e13c4b0261b7e3fdf3516614c1d851507a738acbf3921084270794e0f3a
    - SHA256:754b1ef020c1fb51bd9df6f1b096dd84844eca2c4916daef61731a4a951d56b4
    - SHA1:021228717e4231c78cf52bbd0c0d787018391837 [weak]
    - MD5Sum:ce4e793a440410dfa599578674a9141d [weak]
    - Filesize:20039408 [weak]
E: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/./libnccl2_2.5.4-1+cuda10.1_amd64.deb  File has unexpected size (22972696 != 22974024). Mirror sync in progress? [IP: 192.229.211.70 443]
   Hashes of expected file:
    - SHA512:a1488e248b71de0113888bad78091133847ddd3b4b895acadc1c277dbe7110e37347e83bf5afcea6b7a840dfcaa94c24f5c25b00cac986d6bd154463b74fd50a
    - SHA256:d97322b0a4a59a5fcce23cccd5e9aad1c88f79fb9b3039923dc8b9f9dc2e6607
    - SHA1:eb8471bbd0123118903c9db472f3434acc6622e5 [weak]
    - MD5Sum:e4e650ae3e52b3b35fe34ff1982e0b42 [weak]
    - Filesize:22974024 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

This has been going on for over 12 hours now, so doesn't appear to be a usual transient issue.

```
Digest: sha256:6715c8051917d0e9f46fa7a6cc759a70950c1f229118453bc6cb536e97706342
```

Here's a [link](https://buildkite.com/horovod/horovod/builds/1448#fa49ef46-6f9e-494a-8c0b-d5ccc0966381) to one of the failing nightly builds, for reference.

Please let me know if there's anything on my end that can be done to fix this, I admit to not being a Docker expert.  I've tried `apt-get clean`, adding `apt-get update` to the same line as `apt-get install` and a few other things to try to avoid using any caches, but doesn't seem to help.

Thanks.

**Comment by tgaddair** [comment]
Note that the problem appears to be related to using `NCCL 2.5.4-1+cuda10.1`, the error is fixed by installing `NCCL 2.4.8-1+cuda10.1` instead.

Feel free to close the issue if this is outside the scope of this project.

**Comment by RenaudWasTaken** [comment]
Let me report this to the team in charge of packaging.
Unfortunately it is thanksgiving in the US and I wouldn't expect things to be fixed until Monday.

**Comment by cliffwoolley** [comment]
I'll take a look.  Thanks for the heads up.  I agree that the issue is
unrelated to nvidia-docker, however.

**Comment by cliffwoolley** [comment]
Closing this issue - will track in https://github.com/NVIDIA/nccl/issues/269 .
