### ISSUE TITLE
Ubuntu 20.04 docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

### ISSUE THREAD

**Issue by bokutotu** [NVIDIA/nvidia-docker#1311]
### 1. Issue or feature description
I recently updated ubuntu to 20.04. And I had a problem; nvidia-docker is not available.
I got the following error
```docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu ]]].```

### 2. Steps to reproduce the issue
In response to the above error, I tried to completely uninstall the docker. I used [this site](https://askubuntu.com/questions/935569/how-to-completely-uninstall-docker#:~:text=5%20Answers&text=You%20have%20removed%20Docker%20from%20the%20system%20completely.&text=You%20can%20identify%20the%20packages,%2Dget%20purge%20.) as a reference.
Next, I re-installed docker using [this site](https://illya13.github.io/RL/tutorial/2020/04/27/installing-tensorflow-in-docker-on-ubuntu-20.html) as a reference.
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`
5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - [ ] Any relevant kernel output lines from `dmesg`

 - [ ] Driver information from `nvidia-smi -a`
==============NVSMI LOG==============

Timestamp                           : Tue Jun 16 16:55:16 2020
Driver Version                      : 440.64
CUDA Version                        : 10.2

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Product Name                    : GeForce RTX 2080 Ti
    Product Brand                   : GeForce
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : 1321020043571
    GPU UUID                        : GPU-66d603d7-d3b2-f60f-d187-a6f6a82afb29
    Minor Number                    : 0
    VBIOS Version                   : 90.02.30.00.05
    MultiGPU Board                  : No
    Board ID                        : 0x100
    GPU Part Number                 : 900-1G150-2530-000
    Inforom Version
        Image Version               : G001.0000.02.04
        OEM Object                  : 1.1
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization Mode         : None
        Host VGPU Mode              : N/A
    IBMNPU
        Relaxed Ordering Mode       : N/A
    PCI
        Bus                         : 0x01
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1E0710DE
        Bus Id                      : 00000000:01:00.0
        Sub System Id               : 0x12A410DE
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 1
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays Since Reset         : 0
        Replay Number Rollovers     : 0
        Tx Throughput               : 2000 KB/s
        Rx Throughput               : 2000 KB/s
    Fan Speed                       : 40 %
    Performance State               : P8
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 11011 MiB
        Used                        : 769 MiB
        Free                        : 10242 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 15 MiB
        Free                        : 241 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 1 %
        Memory                      : 3 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    FBC Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            SRAM Correctable        : N/A
            SRAM Uncorrectable      : N/A
            DRAM Correctable        : N/A
            DRAM Uncorrectable      : N/A
        Aggregate
            SRAM Correctable        : N/A
            SRAM Uncorrectable      : N/A
            DRAM Correctable        : N/A
            DRAM Uncorrectable      : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending Page Blacklist      : N/A
    Temperature
        GPU Current Temp            : 36 C
        GPU Shutdown Temp           : 94 C
        GPU Slowdown Temp           : 91 C
        GPU Max Operating Temp      : 89 C
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 22.28 W
        Power Limit                 : 260.00 W
        Default Power Limit         : 260.00 W
        Enforced Power Limit        : 260.00 W
        Min Power Limit             : 100.00 W
        Max Power Limit             : 320.00 W
    Clocks
        Graphics                    : 300 MHz
        SM                          : 300 MHz
        Memory                      : 405 MHz
        Video                       : 540 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 2160 MHz
        SM                          : 2160 MHz
        Memory                      : 7000 MHz
        Video                       : 1950 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 1169
            Type                    : G
            Name                    : /usr/lib/xorg/Xorg
            Used GPU Memory         : 59 MiB
        Process ID                  : 2204
            Type                    : G
            Name                    : /usr/lib/xorg/Xorg
            Used GPU Memory         : 218 MiB
        Process ID                  : 2407
            Type                    : G
            Name                    : /usr/bin/gnome-shell
            Used GPU Memory         : 183 MiB
        Process ID                  : 2997
            Type                    : G
            Name                    : /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=16420760058553398759,1155905022902818744,131072 --enable-crash-reporter=90d13753-4ad7-4622-b2eb-214bb9a90ede, --gpu-preferences=MAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAACAAAAAAAAAA= --shared-files
            Used GPU Memory         : 288 MiB
 - [ ] Docker version from `docker version`
lient:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                         Version                     Architecture                Description
+++-============================================-===========================-===========================-==============================================================================================
un  libgldispatch0-nvidia                        <none>                      <none>                      (no description available)
ii  libnvidia-cfg1-440:amd64                     440.82+really.440.64-0ubunt amd64                       NVIDIA binary OpenGL/GLX configuration library
un  libnvidia-cfg1-any                           <none>                      <none>                      (no description available)
un  libnvidia-common                             <none>                      <none>                      (no description available)
ii  libnvidia-common-440                         440.82+really.440.64-0ubunt all                         Shared files used by the NVIDIA libraries
rc  libnvidia-compute-435:amd64                  435.21-0ubuntu0.18.04.2     amd64                       NVIDIA libcompute package
ii  libnvidia-compute-440:amd64                  440.82+really.440.64-0ubunt amd64                       NVIDIA libcompute package
ii  libnvidia-compute-440:i386                   440.82+really.440.64-0ubunt i386                        NVIDIA libcompute package
ii  libnvidia-container-tools                    1.1.1-1                     amd64                       NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64                   1.1.1-1                     amd64                       NVIDIA container runtime library
un  libnvidia-decode                             <none>                      <none>                      (no description available)
ii  libnvidia-decode-440:amd64                   440.82+really.440.64-0ubunt amd64                       NVIDIA Video Decoding runtime libraries
ii  libnvidia-decode-440:i386                    440.82+really.440.64-0ubunt i386                        NVIDIA Video Decoding runtime libraries
un  libnvidia-encode                             <none>                      <none>                      (no description available)
ii  libnvidia-encode-440:amd64                   440.82+really.440.64-0ubunt amd64                       NVENC Video Encoding runtime library
ii  libnvidia-encode-440:i386                    440.82+really.440.64-0ubunt i386                        NVENC Video Encoding runtime library
un  libnvidia-extra                              <none>                      <none>                      (no description available)
ii  libnvidia-extra-440:amd64                    440.82+really.440.64-0ubunt amd64                       Extra libraries for the NVIDIA driver
un  libnvidia-fbc1                               <none>                      <none>                      (no description available)
ii  libnvidia-fbc1-440:amd64                     440.82+really.440.64-0ubunt amd64                       NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-fbc1-440:i386                      440.82+really.440.64-0ubunt i386                        NVIDIA OpenGL-based Framebuffer Capture runtime library
un  libnvidia-gl                                 <none>                      <none>                      (no description available)
ii  libnvidia-gl-440:amd64                       440.82+really.440.64-0ubunt amd64                       NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
ii  libnvidia-gl-440:i386                        440.82+really.440.64-0ubunt i386                        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
un  libnvidia-ifr1                               <none>                      <none>                      (no description available)
ii  libnvidia-ifr1-440:amd64                     440.82+really.440.64-0ubunt amd64                       NVIDIA OpenGL-based Inband Frame Readback runtime library
ii  libnvidia-ifr1-440:i386                      440.82+really.440.64-0ubunt i386                        NVIDIA OpenGL-based Inband Frame Readback runtime library
ii  libnvidia-ml-dev                             10.1.243-3                  amd64                       NVIDIA Management Library (NVML) development files
un  libnvidia-ml.so.1                            <none>                      <none>                      (no description available)
un  libnvidia-ml1                                <none>                      <none>                      (no description available)
un  libnvidia-tesla-418-ml1                      <none>                      <none>                      (no description available)
un  libnvidia-tesla-440-ml1                      <none>                      <none>                      (no description available)
un  libnvidia-tesla-cuda1                        <none>                      <none>                      (no description available)
un  nvidia-304                                   <none>                      <none>                      (no description available)
un  nvidia-340                                   <none>                      <none>                      (no description available)
un  nvidia-384                                   <none>                      <none>                      (no description available)
un  nvidia-390                                   <none>                      <none>                      (no description available)
un  nvidia-common                                <none>                      <none>                      (no description available)
ii  nvidia-compute-utils-440                     440.82+really.440.64-0ubunt amd64                       NVIDIA compute utilities
ii  nvidia-container-runtime                     3.2.0-1                     amd64                       NVIDIA container runtime
un  nvidia-container-runtime-hook                <none>                      <none>                      (no description available)
ii  nvidia-container-toolkit                     1.1.2-1                     amd64                       NVIDIA container runtime hook
ii  nvidia-cuda-dev                              10.1.243-3                  amd64                       NVIDIA CUDA development files
ii  nvidia-cuda-doc                              10.1.243-3                  all                         NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb                              10.1.243-3                  amd64                       NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit                          10.1.243-3                  amd64                       NVIDIA CUDA development toolkit
ii  nvidia-dkms-440                              440.82+really.440.64-0ubunt amd64                       NVIDIA DKMS package
un  nvidia-dkms-kernel                           <none>                      <none>                      (no description available)
un  nvidia-driver                                <none>                      <none>                      (no description available)
ii  nvidia-driver-440                            440.82+really.440.64-0ubunt amd64                       NVIDIA driver metapackage
un  nvidia-driver-binary                         <none>                      <none>                      (no description available)
un  nvidia-kernel-common                         <none>                      <none>                      (no description available)
ii  nvidia-kernel-common-440                     440.82+really.440.64-0ubunt amd64                       Shared files used with the kernel module
un  nvidia-kernel-source                         <none>                      <none>                      (no description available)
ii  nvidia-kernel-source-440                     440.82+really.440.64-0ubunt amd64                       NVIDIA kernel source package
un  nvidia-legacy-304xx-vdpau-driver             <none>                      <none>                      (no description available)
un  nvidia-legacy-340xx-vdpau-driver             <none>                      <none>                      (no description available)
un  nvidia-libopencl1                            <none>                      <none>                      (no description available)
un  nvidia-libopencl1-dev                        <none>                      <none>                      (no description available)
ii  nvidia-opencl-dev:amd64                      10.1.243-3                  amd64                       NVIDIA OpenCL development files
un  nvidia-opencl-icd                            <none>                      <none>                      (no description available)
un  nvidia-persistenced                          <none>                      <none>                      (no description available)
ii  nvidia-prime                                 0.8.14                      all                         Tools to enable NVIDIA's Prime
ii  nvidia-profiler                              10.1.243-3                  amd64                       NVIDIA Profiler for CUDA and OpenCL
ii  nvidia-settings                              440.64-0ubuntu1             amd64                       Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binary                       <none>                      <none>                      (no description available)
un  nvidia-smi                                   <none>                      <none>                      (no description available)
un  nvidia-tesla-418-driver                      <none>                      <none>                      (no description available)
un  nvidia-tesla-440-driver                      <none>                      <none>                      (no description available)
un  nvidia-utils                                 <none>                      <none>                      (no description available)
ii  nvidia-utils-440                             440.82+really.440.64-0ubunt amd64                       NVIDIA driver support binaries
un  nvidia-vdpau-driver                          <none>                      <none>                      (no description available)
ii  nvidia-visual-profiler                       10.1.243-3                  amd64                       NVIDIA Visual Profiler for CUDA and OpenCL
ii  xserver-xorg-video-nvidia-440                440.82+really.440.64-0ubunt amd64                       NVIDIA binary Xorg driver
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
version: 1.1.1
build date: 2020-05-19T15:15+00:00
build revision: e5d6156aba457559979597c8e3d22c5d8d0622db
build compiler: x86_64-linux-gnu-gcc-7 7.5.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

 - [ ] Docker command, image and tag used
nvidia-docker:latest

**Comment by XufengXufengXufeng** [comment]
If your docker is installed with snap, which appeared in my case, remove it may solve the problem.

In a terminal type in:
`sudo snap list`
if something about docker appeared, it means your docker is installed with docker.

Snap maybe a good software, but I don't have time to figure it out. Uninstall the docker with snap and install a docker in the regular way solved my problem.

In a terminal type in:
`sudo snap remove docker` 

Then install a docker without snap. And then, add the new docker path to system environment.
`export DOCKERPATH=/usr/bin/docker`
`export PATH=$PATH:DOCKERPATH`

**Comment by flydragon2018** [comment]
Ubuntu18.04 , got same issue.

docker run --rm --gpus all nvcr.io/nvidia/tensorrt:19.09-py3 nvidia-smi
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

**Comment by abrar-kh** [comment]
@Hika-Kondo and @flydragon2018 did you guys able to find any solution?
Currently I'm using Ubuntu 20.04 LTS with 
CUDA version 11.1 
Docker version 19.03.13.

**Comment by abrar-kh** [comment]
> @Hika-Kondo and @flydragon2018 did you guys able to find any solution?
> Currently I'm using Ubuntu 20.04 LTS with
> CUDA version 11.1
> Docker version 19.03.13.

I was able to resolve this issue by installing NVidia Container Toolkit.
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

**Comment by revanthsenthil** [comment]
I'm running 22.04 and trying to run 4 docker images that have been pulled from a repository, and I think this error has something to do with the architecture of the PC: but I have a 64-bit, but when I installed the respective NVIDIA drivers, a bunch of `...:i386` packages were installed along with it, which is only possible if there is some 32-bit involvement. NVIDIA packages have `:i386` appended to the end of a package name if it is for a 32-bit system. 

Could this be because possibly, the computer of the image that is being accessed could possibly be 32-bit? Is there any other way to surpass these i386 dependencies?

**Comment by elezar** [comment]
Please see the updated [installation documenation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) and create an issue against https://github.com/NVIDIA/nvidia-container-toolkit if there are still problems.
