### ISSUE TITLE
nvidia docker does not run with winver 20251.1

### ISSUE THREAD

**Issue by tadam98** [NVIDIA/nvidia-docker#1410]
https://github.com/microsoft/WSL/issues/6014#issuecomment-723573300

I installed Windows Insider version 20251.1. And Nvidia docker does not run in wsl2.

Rebuilt my computer. Now the Windows insider version is 20251.1 (downgrade to 2.3.0 did not help)

On the windows host docker 2.5.0.0 was installed.
```
$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.
```

For some reason: 
```
$ sudo service docker stop
docker: unrecognized service
```

It was not so in my previous system.

```
docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERROR[0000] error waiting for container: context canceled
```

And, as requested:
```
~$ ls -la /dev/dxg
crw-rw-rw- 1 root root 245, 0 Nov  8 05:49 /dev/dxg
```

That docker you I am running is output of ls -la $(which docker)
`-rwxr-xr-x 1 root root 89213816 Oct 14 19:52 /usr/bin/docker`
```
docker --version
Docker version 19.03.6, build 369ce74a3c
```

```
python
import tensorflow as tf
tf.__version__
```
**'1.14.0'**
tf.test.is_gpu_available()
2020-11-08 14:32:14.364926: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:0a:00.0
**True**
`tf.test.gpu_device_name()`
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:0a:00.0
2020-11-08 14:32:25.081122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:0 with 9630 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:0a:00.0, compute capability: 7.5)
**'/device:GPU:0'**

As can be seen, the GPU is seen in wsl2. 
I just have the docker problem.

**Comment by nalpalhao** [comment]
Same here, also the classic BlackScholes cuda sample (with make) on wsl stopped working.

**Comment by tadam98** [comment]
And 20461.1 that **did** work, is no where to be found. Shame on them.
I think Microsoft **must** leave 2 versions behind available. They are *killing* my work.

Further, restoring Windows Insider disk clones could be *very* problematic as it does not always work with latest model motherboards.

Mickey

**Comment by tadam98** [comment]
Microsoft just released 20257.1 any opinions ?
Mickey

**Comment by klueska** [comment]
@dualvtable is the best to comment on this.

**Comment by nalpalhao** [comment]
@tadam98 Just updated to 20257.1, after reinstalling everything the problem got solved.

**Comment by tadam98** [comment]
@nalpalhao nvidia docker fails for me. Can you provide a URL or the list of installation procedures on a virgin wsl2 ?

**Comment by nalpalhao** [comment]
@tadam98 So I'm using the [CUDA on WSL](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) documentation, so **no docker desktop** here.

After updating to winver 20257.1, I also had to update the wsl package and more:
- Re ran the instaler from  [Microsoft Documentation](https://docs.microsoft.com/pt-pt/windows/wsl/install-win10) ([update package link](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi));
- After that and just in case, ran the: `wsl --update` on power shell as administrator;
- Got the Ubuntu 18.04 distribution from the store;
- Just in case again, reinstalled the [Nvidia Driver](https://developer.nvidia.com/cuda/wsl);
- Restart your machine;
#
After these reinstallations I was able to follow the CUDA on WSL documentation step by step sucessfully, just some notes:
- To run the BlackScholes cuda example successfully (with make) I had to restart the wsl service ( `wsl --shutdown` );
- Now the command `sudo service docker stop` actually works;
- To run the `docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark` command succesfully I again, had to restart the wsl service;
#
Now docker should be able to recognize your gpu (as explicitly said in the documentation  use `curl https://get.docker.com | sh` to install docker).

Hope it helps,
Nuno

**Comment by tadam98** [comment]
1. BlackScholes  runs fine on the WSL2. So does tensorflow
2. Only the nvidia container does not work.
3. Also, According to their suggested procedure, I did not install docker.io as for WSL2 it giges a warning/advise to rely on the Docker 2.x installed under the windows environment below.
4. In this case the sudo service docker stop does not work as the docker service is not in the ubuntu.

I will follow your procedure and share.

Mickey

**Comment by tadam98** [comment]
I uninstalled the windows docker.
And I am getting **docker: unrecognized service** in the wsl2 afte rthe installation procedure.

**Comment by tadam98** [comment]
Upgraded yo 20257.1 still the same. 
```
docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container: context canceled
```
On tensorflow it is ok:

 ```
tf.test.gpu_device_name()
2020-11-13 00:03:57.233504: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:991] could not open file to read NUMA node: /sys/bus/pci/devices/0000:0a:00.0/numa_node
2020-11-13 00:03:22.246221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:0 with 9630 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:0a:00.0, compute capability: 7.5)
2020-11-13 00:03:22.247955: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55b4c5b9edc0 executing computations on platform CUDA. Devices:
2020-11-13 00:03:22.247982: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
True
```

**Comment by tadam98** [comment]
This makes it work.
Basically install docker on wsl2.
https://dev.to/bartr/install-docker-on-windows-subsystem-for-linux-v2-ubuntu-5dl7 

After restart of wsl2 do the following procedure:
```
$ docker ps
$ docker ps -aq
$ docker stop $(docker ps -aq)
$ docker stop # dockers reported by ps
$ rm ~/.docker/config.json
$ sudo service docker stop
$ sudo service docker start
$ sudo mkdir /sys/fs/cgroup/systemd
$ sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
$ docker ps
$ docker run hello-world
$ docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
GPU Device 0: "GeForce RTX 2080 Ti" with compute capability 7.5

> Compute 7.5 CUDA device: [GeForce RTX 2080 Ti]
69632 bodies, total time for 10 iterations: 117.583 ms
= 412.357 billion interactions per second
= 8247.147 single-precision GFLOP/s at 20 flops per interaction
```

**Comment by tadam98** [comment]
Windows insider updated to 20262.1
With the update, the regular nvidia driver was re-installed. Not good for wsl2.
Also, nvidia issued a *new* driver that you should install in windows:
https://developer.nvidia.com/cuda/wsl
The new drive is 465.12
Download and install it.
***You must reboot after the install or wsl2 will not see the gpu as of yet*.**
Start wsl2
```
$ python
> import tensorflow as tf
>  tf.test.is_gpu_available()
2020-11-19 17:15:13.395676: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
True
```
Then do the above docker procedures to check that the docker aslo works.
In my case, it works fine.
