### ISSUE TITLE
code=35 cudaErrorInsufficientDriver

### ISSUE THREAD

**Issue by Melliti** [NVIDIA/nvidia-docker#1437]
I'm facing an issue with the user guide from nvidia:

https://docs.nvidia.com/cuda/wsl-user-guide/index.html

after compiling resourses with the makefile, I try to run ./BlackScholes but i have this error:
```
CUDA error at ../../common/inc/helper_cuda.h:777 code=35(cudaErrorInsufficientDriver) "cudaGetDeviceCount(&device_count)"
```

I'm running the program on **Ubuntu 18.04** (On windows with wsl2) 
**Nvidia driver** version **465.21**
Windows 10 Version 1909 **build 18363**
CUDA **11.0.228**

I supposed it's due to a version mismatch

**Comment by lexus2k** [comment]
The same issue is true for me also.
I went through many instructions, did setup several times from scratch, but no success.
My PC currently runs Windows 10 latest official release build 19042 20H2 with WSL2 support and CUDA virtualization support. 
But every time I get `CUDA error at ../../common/inc/helper_cuda.h:777 code=35(cudaErrorInsufficientDriver) "cudaGetDeviceCount(&device_count)"`.

I installed Ubuntu packages from here: `http://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/`, and NVidia driver with WSL support as NVidia recommends.

**Comment by jjneuro** [comment]
Beginner here.
I have the same issue as users Melliti & lexus2k
Using WSL2
Is it possible that it is not due to a version mismatch, but is simply not able to read in the NVIDIA driver? 
Thanks to anyone who can help.

**Comment by lexus2k** [comment]
@jjneuro  Hi,

Finally I've figured out the root cause. **You must be the member of Microsoft Insider Program**.
CUDA support in WSL2 available only in Windows build 20140 and later. But official mass production releases of Windows are now around 19042 build. 
After installing Insider build, I was able to run CUDA examples in Ubuntu WSL2.  But now I have another issue with training detectnet_v2: it starts, pass Epoch 1, and then radomly freezes somewhere - it is impossible to stop tlt-train by pressing CTRL+C. The only way to stop it and start again is to use kill -9.

**Comment by klueska** [comment]
Yes. As the instructions linke below state, you need to register with the Insider program and build version 20145 or higher in order for this to work.

https://docs.nvidia.com/cuda/wsl-user-guide/index.html#getting-started

**Comment by zzjin** [comment]
when upgrade to win insider 21327, previous worked cuda driver broken again.
shows:
`CUDA error at ../../common/inc/helper_cuda.h:777 code=35(cudaErrorInsufficientDriver) "cudaGetDeviceCount(&device_count)`

**Comment by omaratta212** [comment]
I have the same issue on WSL2 windows insider 21327

**Comment by zzjin** [comment]
https://github.com/microsoft/WSL/issues/6014 do a fresh re-install fix.

**Comment by zzjin** [comment]
https://github.com/microsoft/WSL/issues/6014 do a fresh re-install fix.

**Comment by ahmadelsallab** [comment]
I had the same issue. It seems some environment variables in windows are gone with the update. I just re-run the driver installation again, and it fixed the issue:


https://docs.nvidia.com/cuda/wsl-user-guide/index.html

_"Download the NVIDIA Driver from the download section on the CUDA on WSL page. Choose the appropriate driver depending on the type of NVIDIA GPU in your system - GeForce and Quadro.

Install the driver using the executable. This is the only driver you need to install."_

**Comment by Real-Karisch** [comment]
Having the same issue with windows build 21327 and nvidia driver 470.05. I tried to revert to windows build 21286 but it said that would require deleting all files and settings, which I'm not willing to do. This issue has clearly happened in the past. Any idea how long it took to resolve it? I feel like my only option is just to wait it out at this point.

**Comment by Real-Karisch** [comment]
Following up to say that the issue is fixed after installing all recommended updates in Windows Update, reinstalling the 470.05 driver with a clean install and restarting.

**Comment by janwaltl** [comment]
I did find this thread while having the same issue.

I had the latest Insider build, latest NVIDIA drivers and was still getting `code=35`.

**What finally helped me was to update the Linux(Debian in my case) kernel**:

1. Run `uname -a` and see what version you have. I had `4.19.104` which did not work.
2. Close WSL, run `wsl --update` from powershell as admin.
3. Restart WSL with `wsl --shutdown` and start a new console.
4. Check `uname -a` again, it shows `5.4.91` for me currently and **more importantly everything is working again!**.

Hope it helps you :)
