### ISSUE TITLE
Driver specific CUDA remnants remain inside nvidia/cuda docker image builds.

### ISSUE THREAD

**Issue by jimfcarroll** [NVIDIA/nvidia-docker#1488]
The base docker images for `nvidia/cuda` have remnants of the drivers from the machine they were built on. For example, if you run: `nvidia-docker run -it --rm nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04 bash` on a machine with driver version 450.102.04, and then run `ls -l | grep cuda` from inside `/lib/x86_64-linux-gnu` you get:

```
lrwxrwxrwx  1 root root         12 Apr 13 16:08 libcuda.so -> libcuda.so.1
lrwxrwxrwx  1 root root         20 Apr 13 16:09 libcuda.so.1 -> libcuda.so.460.32.03
-rw-r--r--  1 root root   19615656 Dec 29 06:58 libcuda.so.450.102.04
-rw-r--r--  1 root root   21803296 Dec 27 19:03 libcuda.so.460.32.03
```

Notice, there are 2 versions of `libcuda.so`. One identified with the driver version of the machine the original image was built on (460.32.03) and one with the version from the machine the image was run on (450.102.04). Notice also, the WRONG one is linked. This is RUNNING on a machine with driver 450.102.04.

You get similar results if you grep for `nvidia` instead of `cuda`:
```
...
lrwxrwxrwx  1 root root         37 Apr 13 16:09 libnvidia-ptxjitcompiler.so.1 -> libnvidia-ptxjitcompiler.so.460.32.03
-rw-r--r--  1 root root    9947144 Dec 29 06:47 libnvidia-ptxjitcompiler.so.450.102.04
-rw-r--r--  1 root root   10516984 Dec 27 18:55 libnvidia-ptxjitcompiler.so.460.32.03
```

Notes: 
- We're running a 20.04 container on an Ubuntu 18.04 host, which SHOULD work given the drivers are compatible with compute 61 and CUDA 11.2.
- docker version is 20.10.5
- from `apt list --installed` : nvidia-docker2/bionic,now 2.5.0-1 all [installed]
- I don't believe this is a problem with the image. If I run the image using the default runtime and look in the same directory, then there are NO libraries for `cuda` or `nvidia`. They only appear and are incorrect when I use the `nvidia` docker runtime.

**Comment by klueska** [comment]
This is a known issue. You need to disable the nvidia as your default container runtime when building.
Alternatively, unset all NVIDIA_* variables so that no library injection occurs during the build.

**Comment by jimfcarroll** [comment]
@klueska thanks for the response. Is there a more fine-grained alternative work around? I need those libraries to build against as well as the fact that the build runs tests and so also need them to run in the same container session.

**Comment by klueska** [comment]
At the end of your Dockerfile you can explicitly `umount` every library that was injected and then `rm` it.

**Comment by jimfcarroll** [comment]
Wow. Thanks! Much easier than the route I was taking. I didn't realize they were using the mount mechanism. I replaced `ldconfig` n the container with a script that modified the links after running the original.

**Comment by jimfcarroll** [comment]
That doesn't fix the problem. It puts back the incorrect driver version on subsequent runs of the image. It also requires that the docker container be running/building in privileged mode in order to run umount.

**Comment by klueska** [comment]
Maybe I’m misunderstanding something. Where are the 450 versions of the driver libs coming from? Are those „ghost“ libraries in the official image? If so, that’s definitely a problem.

In the past that has only happened when some third party has taken the official images and extended them (like I thought you were doing).

If they‘re actually in the official base image, then we need to fix that on our end.

**Comment by klueska** [comment]
From rereading your description, they don’t appear to be in the image since running without the nvidia runtime, you don’t see them.

That means the only way they could be getting in there is if they are injected from the host.

Are you sure that you don’t somehow have both sets of libraries on your host, such that both are being injected?

**Comment by jimfcarroll** [comment]
`sudo find / -name "*460.32*"` results in
```
/var/lib/docker/overlay2/8400cfbba3d555b97fc967c57e94deb372a9a5d1072db737de7b9b59fc24f11f/diff/usr/local/cuda-11.2/compat/libnvidia-ptxjitcompiler.so.460.32.03
/var/lib/docker/overlay2/8400cfbba3d555b97fc967c57e94deb372a9a5d1072db737de7b9b59fc24f11f/diff/usr/local/cuda-11.2/compat/libcuda.so.460.32.03
```
Those go away when I delete all volumes but come back when I run an nvidia/cuda image. There are no 460 drivers on the machine. See the `find` above and also `sudo apt list --installed | grep 460` results in nothing.

But this doesn't happen on a different 18.04 machine I tested. So it must be something local. I'll close the issue given it's apparently my machine but if you have any other suggestion as to where to look, I'd appreciate it.

**Comment by jimfcarroll** [comment]
I purged *nvida* and docker and reinstalled the drivers from scratch using 460. It's working now. Thanks.
