### ISSUE TITLE
buildkit loose the binding of the nvidia driver libraries available on the host

### ISSUE THREAD

**Issue by rafraph** [NVIDIA/nvidia-docker#1504]
### 1. Issue or feature description
When building a container (docker 19.03) that should use CUDA it should bind the nvidia driver libraries available on the host into the container.
It is working perfectly with legacy build. But with buildkit in some cases it loose the binding.

**Explanation**
The file that loose binding is the "libcuda.so" which is the CUDA driver library.
libcuda.so is a simlink to libcuda.so.1 which is a symlink to libcuda.so.version (in my case libcuda.so.455.32.00)
This issue cause the linking to fail with this error:

```
 /usr/lib/x86_64-linux-gnu/libcuda.so: file not recognized: File truncated
 collect2: error: ld returned 1 exit status
```
When prinitng the file size during the build, with the following command:
`RUN ls -l /usr/lib/x86_64-linux-gnu/libcuda.so.455.32.00`
With legacy build we get:
`-rw-r--r-- 1 root root 21074296 Oct 14  2020 /usr/lib/x86_64-linux-gnu/libcuda.so.455.32.00`
but with buildkit we get size of zero:
`-rw-r--r-- 1 root root 0 Mar  1 15:18 /usr/lib/x86_64-linux-gnu/libcuda.so.455.32.00`

### 2. Steps to reproduce the issue
**Dockerfile**
```
FROM nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04
RUN ls -l /usr/lib/x86_64-linux-gnu/libcuda.so.455.32.00
CMD ["/bin/bash"]
```
**Command:**
`docker build --progress=plain -t test .`

**Result without buildkit:**
```
Sending build context to Docker daemon  4.968GB
Step 1/3 : FROM nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04
11.1-cudnn8-devel-ubuntu18.04: Pulling from nvidia/cuda
f22ccc0b8772: Already exists
3cf8fb62ba5f: Already exists
e80c964ece6a: Already exists
8a451ac89a87: Already exists
c563160b1f64: Already exists
596a46902202: Already exists
aa0805983180: Already exists
5718c3da35a0: Already exists
003637b0851a: Already exists
Digest: sha256:eaf9028c8becaaee2f0ad926fcd5edb80c7f937d58d6c5d069731f8f9afc2152
Status: Downloaded newer image for nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04
 ---> a12c244542fe
Step 2/3 : RUN ls -l /usr/lib/x86_64-linux-gnu/libcuda.so.455.32.00
 ---> Running in fb3bff4aebb4
-rw-r--r-- 1 root root 21074296 Oct 14  2020 /usr/lib/x86_64-linux-gnu/libcuda.so.455.32.00
Removing intermediate container fb3bff4aebb4
 ---> 5613878680ba
Step 3/3 : CMD ["/bin/bash"]
 ---> Running in 06022742780f
Removing intermediate container 06022742780f
 ---> 180b8e423aa1
Successfully built 180b8e423aa1
Successfully tagged test:latest
```
**Result with buildkit:**
```
#1 [internal] load build definition from Dockerfile.test
#1 transferring dockerfile: 170B done
#1 DONE 0.1s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.1s

#3 [internal] load metadata for docker.io/nvidia/cuda:11.1-cudnn8-devel-ubu...
#3 DONE 0.7s

#4 [1/2] FROM docker.io/nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04@sha256:ea...
#4 CACHED

#5 [2/2] RUN ls -l /usr/lib/x86_64-linux-gnu/libcuda.so.455.32.00
#5 0.273 ls: cannot access '/usr/lib/x86_64-linux-gnu/libcuda.so.455.32.00': No such file or directory
#5 ERROR: executor failed running [/bin/sh -c ls -l /usr/lib/x86_64-linux-gnu/libcuda.so.455.32.00]: runc did not terminate sucessfully
------
 > [2/2] RUN ls -l /usr/lib/x86_64-linux-gnu/libcuda.so.455.32.00:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c ls -l /usr/lib/x86_64-linux-gnu/libcuda.so.455.32.00]: runc did not terminate sucessfully
```

**Comment by oliviawindsir** [comment]
@rafraph have you found the solution and explanation to this issue? I am also facing the same problem.

**Comment by rafraph** [comment]
No. Since this bug still open I think this is still a bug

**Comment by oliviawindsir** [comment]
@rafraph I have solved my issue. I have a post [here](https://forums.developer.nvidia.com/t/libcuda-so-file-not-recognized-file-truncated-when-make-during-a-docker-build/183845/5?u=wsong) for your reference. 

In short, it was due to me setting my docker runtime to use `nvidia-container-runtime`. Removing that from the `daemon.json` helps.

**Comment by klueska** [comment]
Building images with the `nvidia-container-runtime` set as the default runtime is unsupported and will lead to issues down the road when you try to actually run containers against those images.

The problem is that the `nvidia-container-runtime` will inject whatever NVIDIA libraries you have installed on our build system into the container and then leave `ghost` versions of those libraries around (i.e. files with 0 bytes representing those libraries) inside the resulting image. This happens because the `nvidia-container-runtime` bind-mounts these libraries "behind the back" of docker so it doesn't know how to unmount them properly when finalizing the image.

When you then try to run a container based on one of these images on a machine with a different driver version, you end up with *2* sets of NVIDIA libraries inside the container (i.e. the "ghost" libraries from the build machine, and the current libraries from the current host machine). This then obviously causes problems if the ghost libraries are chosen over the current host's libraries.

So the "solution" to this issue is that you should *not* be building images with the `nvidia-container-runtime` set (with or without `buildkit` enabled). If you need to compile against cuda libraries, then you should be installing the stub libraries and compiling against them instead.

**Comment by unphased** [comment]
@klueska Could you please elaborate on what you mean by this?

> installing the stub libraries and compiling against them instead.

My team is working on a lot of complex software that has CUDA as a dependency so there is no way for me to split the build into a CUDA section and a regular section, and I am trying to implement buildkit into the build system and I'm alarmed to learn that it seems totally unsupported. 

But also what you are stating indicates that our approach (pre-buildkit) is also very flawed. I know it is because it will fail in painful ways when the runtime environment does not perfectly match that of the machine which ran the docker build, but this is worked around because we use the same flash image on the devices which build the image and which run it in containers. 

@klueska What are the stub libraries?

**Comment by klueska** [comment]
I mean linking against the stub versions of e.g. `libcuda.so` instead of relying on having the "real" `libcuda.so` injected and available inside the container at build time.

For example, these stubs live here, in the latest 11.7.1-devel image for ubuntu20.04:
```
$ docker run --rm nvidia/cuda:11.7.1-devel-ubuntu20.04 ls -la /usr/local/cuda-11.7/targets/sbsa-linux/lib/stubs
total 2288
drwxr-xr-x 2 root root   4096 Aug 11 23:14 .
drwxr-xr-x 1 root root   4096 Aug 11 23:14 ..
-rw-r--r-- 1 root root  62672 May 20 03:35 libcublas.so
-rw-r--r-- 1 root root  25808 May 20 03:35 libcublasLt.so
-rw-r--r-- 1 root root  58208 Jun  9 01:14 libcuda.so
-rw-r--r-- 1 root root   9424 May 20 02:57 libcufft.so
-rw-r--r-- 1 root root  13520 May 20 02:57 libcufftw.so
-rw-r--r-- 1 root root   9424 May 20 03:06 libcurand.so
-rw-r--r-- 1 root root 124112 May 20 03:18 libcusolver.so
-rw-r--r-- 1 root root  34000 May 20 03:18 libcusolverMg.so
-rw-r--r-- 1 root root  66768 May 20 02:43 libcusparse.so
-rw-r--r-- 1 root root   5328 May 20 02:52 libnppc.so
-rw-r--r-- 1 root root 279760 May 20 02:52 libnppial.so
-rw-r--r-- 1 root root 144592 May 20 02:52 libnppicc.so
-rw-r--r-- 1 root root 193744 May 20 02:52 libnppidei.so
-rw-r--r-- 1 root root 275664 May 20 02:52 libnppif.so
-rw-r--r-- 1 root root  95440 May 20 02:52 libnppig.so
-rw-r--r-- 1 root root  42192 May 20 02:52 libnppim.so
-rw-r--r-- 1 root root 455888 May 20 02:52 libnppist.so
-rw-r--r-- 1 root root   9424 May 20 02:52 libnppisu.so
-rw-r--r-- 1 root root  58576 May 20 02:52 libnppitc.so
-rw-r--r-- 1 root root 238800 May 20 02:52 libnpps.so
-rw-r--r-- 1 root root  46816 May 20 02:44 libnvidia-ml.so
-rw-r--r-- 1 root root  13520 May 20 03:04 libnvjpeg.so
-rw-r--r-- 1 root root   5328 Jun  9 00:50 libnvrtc.so
```

**Comment by unphased** [comment]
@klueska Thank you. I do see that these stub .so's exist in this location, but simply adding them to `$LD_LIBRARY_PATH` is not accomplishing anything. 

See this buildkit log from something I attempted: 

```
20:01:28  #87 [icam-build 2/9] RUN python3 -c "import torch;print(torch.cuda.is_availa...
20:01:30  #87 1.066 Traceback (most recent call last):
20:01:30  #87 1.066   File "<string>", line 1, in <module>
20:01:30  #87 1.066   File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 189, in <module>
20:01:30  #87 1.066     _load_global_deps()
20:01:30  #87 1.066   File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 142, in _load_global_deps
20:01:30  #87 1.066     ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
20:01:30  #87 1.066   File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
20:01:30  #87 1.066     self._handle = _dlopen(self._name, mode)
20:01:30  #87 1.066 OSError: libcurand.so.10: cannot open shared object file: No such file or directory
20:01:30  #87 ERROR: executor failed running [/bin/bash -c python3 -c "import torch;print(torch.cuda.is_available())"]: runc did not terminate sucessfully
20:01:30  ------
20:01:30   > [icam-build 2/9] RUN python3 -c "import torch;print(torch.cuda.is_available())":
20:01:30  ------
20:01:30  failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to build LLB: executor failed running [/bin/bash -c python3 -c "import torch;print(torch.cuda.is_available())"]: runc did not terminate sucessfully
```

How can we "install the stub libraries"? That is clearly what's stopping me on this path. 

I feel like I need to give up on this path and just transition our build into a scripted container build which will not have this issue, but that is much less maintainable than a dockerfile. There's a huge problem with that, which is it's going to be tricky to extricate the ccache cache dir out into the container. And ccache was the whole reason I needed to switch to buildkit.

**Comment by klueska** [comment]
LD_LIBRARY_PATJ is a runtime environment variable used to point your binary at extra folders it can look for shared libraries in.

The build / link time equivalent flag is called LIBRARY_PATH

**Comment by klueska** [comment]
Maybe I’m confused about what you are trying to do during your build. Are you trying to actually execute a Binary that relies on CUDA? That is not going to work with the stubs (or while building a container with docker in general). The stubs are just there so that linking will succeed when building an executable with gcc.

**Comment by unphased** [comment]
Yes I understand that the stubs are just to allow compilation to take place. 

Getting the stubs properly "replaced" with host libs during runtime would be the second half of the equation and I was just exploring the possibility of the first half (allowing the compile to take place). 

So far not having much luck with the first half.

**Comment by pooya-mohammadi** [comment]
@unphased were you able to solve the issue?

**Comment by pooya-mohammadi** [comment]
I finally put the compile commands in command and at each up time it compiles the cuda codes

**Comment by pooya-mohammadi** [comment]
@unphased 
docker-run and docker commit is also a good idea.
I did the following:
I created a build.sh script which contained all the compile commands which required cuda.
Then I did the following:
```
RUN chmod +x build.sh 
CMD ["bash", "-c", "./build.sh; python entrypoint.py"]
```
It runs the compile script(build.sh) in the command which has access to nvidia.
