### ISSUE TITLE
CUDA is not detected by cmake.  Building without it...

### ISSUE THREAD

**Issue by jeremy-rutman** [NVIDIA/nvidia-docker#153]
I am trying to build a container with caffe, using a gpu.

I got the following output during the caffe build - 

```
CMake Warning at cmake/Dependencies.cmake:63 (message):
  -- CUDA is not detected by cmake.  Building without it...
```

Looking at the path in the container
```
root@3f2a6ff54c23:/workspace# ls /usr/local/cuda
LICENSE  README  doc  lib64  targets  version.txt
```
I see its not the same as on the original machine
```
root@brainik80a:/home/jeremy# ls /usr/local/cuda
bin  doc  extras  include  jre  lib  lib64  libnsight  libnvvp  nvvm  pkgconfig  samples  share  src  tools  version.txt
```
so I guess the original docker base 

```
FROM nvidia/cuda:7.5-cudnn5-runtime
```
is not installing the full cuda libs for some reason.  Is this normal behavior? Is there something else I need to do to get the cuda libs recognized by the caffe install?

Crosspost - 
https://groups.google.com/forum/#!topic/caffe-users/FVEdXNBHlPM

**Comment by flx42** [comment]
You want `nvidia/cuda:7.5-cudnn5-devel`
The `runtime` images are useful if you already have deb/rpm/pip packages compiled for your project.

**Comment by jeremy-rutman** [comment]
when I try 
`FROM nvidia/cuda:7.5-cudnn5-devel
`
as you suggested, I hit an error in the caffe compile
`F0726 18:35:44.707867   675 syncedmem.hpp:18] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
`
The caffe build does find cuda this time:
```
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   42cd785
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
--
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
--
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.54)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.5.0)
--   lmdb              :   Yes (ver. 0.9.10)
--   LevelDB           :   Yes (ver. 1.15)
--   Snappy            :   Yes (ver. 1.1.0)
--   OpenCV            :   Yes (ver. 2.4.8)
--   CUDA              :   Yes (ver. 7.5)
--
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_20 sm_21 sm_30 sm_35 sm_50
--   cuDNN             :   Yes (ver. 5.0.5)

```
any help appreciated

**Comment by jeremy-rutman** [comment]
I see there's a readymade caffe+cuda dockerfile here
https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/caffe/0.14/Dockerfile
but as I was interested in some compile options (namely, allowing python layers, using the cmake option  -DBUILD_python_layer=ON)  I blv. I need to start from the nvidia/cuda:7.5-cudnn5-devel image and compile caffe from there.

**Comment by flx42** [comment]
@jeremy-rutman the version of caffe we provide is our own fork of BVLC/caffe:
https://github.com/NVIDIA/caffe
But I believe we should have python layers enabled, since this image is used as a base for DIGITS.

There is also an official dockerfile from BVLC/caffe:
https://github.com/BVLC/caffe/blob/master/docker/standalone/gpu/Dockerfile

For your problem above, your driver version might be too old to run CUDA 7.5 code.

**Comment by jeremy-rutman** [comment]
I checked the driver version with nvidia-smi -q and find driver version 352.39 which is listed as the minimum required version for cuda 7.5 .  I did the baremetal install in standard fashion from the local runfile cuda_7.5.18_linux.run  provided [here](https://developer.nvidia.com/cuda-downloads) - is there something else I should check? 
I am a little leery about moving to a fork since I;d like to keep up to date with the main branch but will try the bvlc dockerfile

**Comment by flx42** [comment]
NVIDIA/caffe **is** the fork. BVLC/caffe is the original caffe.

**Comment by jeremy-rutman** [comment]
s that's what i meant, i'll try the bvlc first instead of the nvidia fork.  Do you have any ideas why , with the 352.39 driver, i hit the compile error?

**Comment by flx42** [comment]
Are you really hitting this error when compiling? This should only happen executing caffe code.

You cannot have a Dockerfile step that uses GPU code unfortunately. But building a GPU application like caffe doesn't require a GPU, it just requires the compiler toolchain.

**Comment by jeremy-rutman** [comment]
ok the error was i blv. from the make runtest  - so I will try the dockerfile without make runtest and see if the caffe.set_gpu works now that the image is from the devel and not runtime

**Comment by jeremy-rutman** [comment]
removing the make runtest lets the image build  - but now i just get the same error when i try to set the device:

```
In [2]: caffe.set_mode_gpu()
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0727 19:10:24.215581   107 common.cpp:113] Cannot create Cublas handle. Cublas won't be available.
E0727 19:10:24.215759   107 common.cpp:120] Cannot create Curand generator. Curand won't be available.

In [3]: caffe.set_device(0)
F0727 19:10:38.562382   107 common.cpp:151] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
Aborted

```

**Comment by flx42** [comment]
What's your command when running the caffe container?

**Comment by jeremy-rutman** [comment]
whoops that last one is my bad, you got it - docker run instead of nvidia-docker run.  When I run the image properly then caffe.set_device is fine - thanks for your patience and help

**Comment by flx42** [comment]
No problem, glad to know it works now!
