### ISSUE TITLE
could not select device driver "" with capabilities: [[gpu]]

### ISSUE THREAD

**Issue by minertom** [NVIDIA/nvidia-docker#1591]
Followed the instructions for loading the TensorRT Nvidia docker file at

[https://developer.nvidia.com/blog/real-time-nlp-with-bert-using-tensorrt-updated/](url)

Had to use cuda 11.5 as opposed to cuda 11.3. Used the following:

`bash docker/build.sh --file docker/ubuntu-18.04.Dockerfile --tag tensorrt-ubuntu18.04-cuda11.5`

There is a docker image, as the result of "docker images" is
`tensorrt-ubuntu18.04-cuda11.5   latest                            454b50ab7609   21 minutes ago      15.4GB`
Actually, there are additional docker images and I am hoping that they are not interfering.

Built the docker file correctly as there is a file in the docker directory "ubuntu-18.04.Dockerfile". 

Running 
`bash docker/launch.sh --tag tensorrt-ubuntu18.04-cuda11.5 --gpus all`

I get the error 
`docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].`

Docker seems to be running.

`sudo snap services docker'

'Service     stertup current Notes'

'docker.dockerd enabled active -`

How to proceed?

Thank You
Tom

**Comment by elezar** [comment]
@minertom is the NVIDIA Container Toolkit installed as per https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#id2

Does running a simple GPU container such as:
```
docker run --gpus all ubuntu nvidia-smi -L
```
show the same output as `nvidia-smi -L` running on the host?

**Comment by minertom** [comment]
elezar,

Thank you for the quick reply. 

No, the NVIDIA container toolkit was not installed.  it was not listed in the instructions listed in [https://github.com/NVIDIA/nvidia-docker/issues/url](url).

However, I did install it and it solved the problem.

Thank You
Tom
