### ISSUE TITLE
"/usr/local/nvidia/bin" is not available in Docker image

### ISSUE THREAD

**Issue by somum** [NVIDIA/nvidia-docker#1597]
In my machine I tried the command :

1. **docker run -it --gpus all nvidia/cuda:11.4.0-devel-ubuntu20.04 nvidia-smi**

output I got:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:0C:00.0 Off |                  N/A |
|  0%   50C    P8    32W / 350W |     19MiB / 24265MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:0D:00.0 Off |                  N/A |
|  0%   44C    P8    29W / 350W |      5MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

But when I am using the docker image.
Dockerfile:
```
FROM nvidia/cuda:11.4.0-devel-ubuntu20.04

RUN apt-get -y update
RUN apt-get -y install python3-pip

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app 
ADD . /app

# Install the dependencies
RUN pip install -r requirements.txt

# run the command to start uWSGI
CMD ["uwsgi", "app.ini"]
```  

The app is running but its not using the GPU. Showing the following error:

**ERROR:**

```
flask    | 2022-01-27 08:40:08.729983: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
flask    | 2022-01-27 08:40:08.730033: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
flask    | 2022-01-27 08:40:08.730043: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
flask    | 2022-01-27 08:40:08.730069: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
flask    | 2022-01-27 08:40:08.730075: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
```

**Comment by hoanghonn** [comment]
Same issue here. Any updates on this?

**Comment by elezar** [comment]
The `nvidia/cuda:11.4.0-devel-ubuntu20.04` does not include `libcusolver` or `libcudnn`. 

You could use the `cudnn` images: https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=11.4.0-cudnn

As a matter of interest, would the `tensorflow` images work directly? If not, consider checking how they install the required dependencies:
https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile

**Comment by isacmoura** [comment]
I used @elezar suggestion, and now it is working fine. In my case, I was using `nvidia/cuda:11.8.0-devel-ubuntu20.04` image so I just added `cudnn` to my image resulting in `nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04`.

**Comment by apcode** [comment]
I am having the same problem but have the cudnn version:
`docker run -it --gpus all --rm nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04 nvidia-smi` works.

However:
`docker run -it --gpus all --rm nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04 /bin/bash`

```> echo $LD_LIBRARY_PATH
/usr/local/nvidia/lib:/usr/local/nvidia/lib64

> ls /usr/local
bin  cuda  cuda-11  cuda-11.8  etc  games  include  lib  man  sbin  share  src

> ls /usr/local/cuda/lib64
cmake                     libcufft.so.10                libcupti.so.2022.3.0         libnppc_static.a         libnppim.so.11.8.0.86   libnvblas.so.11.11.3.6
libOpenCL.so              libcufft.so.10.9.0.58         libcupti_static.a            libnppial.so             libnppim_static.a       libnvjpeg.so
libOpenCL.so.1            libcufft_static.a             libcurand.so                 libnppial.so.11          libnppist.so            libnvjpeg.so.11
libOpenCL.so.1.0          libcufft_static_nocallback.a  libcurand.so.10              libnppial.so.11.8.0.86   libnppist.so.11         libnvjpeg.so.11.9.0.86
libOpenCL.so.1.0.0        libcufftw.so                  libcurand.so.10.3.0.86       libnppial_static.a       libnppist.so.11.8.0.86  libnvjpeg_static.a
libaccinj64.so            libcufftw.so.10               libcurand_static.a           libnppicc.so             libnppist_static.a      libnvperf_host.so
libaccinj64.so.11.8       libcufftw.so.10.9.0.58        libcusolver.so               libnppicc.so.11          libnppisu.so            libnvperf_host_static.a
libaccinj64.so.11.8.87    libcufftw_static.a            libcusolver.so.11            libnppicc.so.11.8.0.86   libnppisu.so.11         libnvperf_target.so
libcheckpoint.so          libcufile.so                  libcusolver.so.11.4.1.48     libnppicc_static.a       libnppisu.so.11.8.0.86  libnvptxcompiler_static.a
libcublas.so              libcufile.so.0                libcusolverMg.so             libnppidei.so            libnppisu_static.a      libnvrtc-builtins.so
libcublas.so.11           libcufile.so.1.4.0            libcusolverMg.so.11          libnppidei.so.11         libnppitc.so            libnvrtc-builtins.so.11.8
libcublas.so.11.11.3.6    libcufile_rdma.so             libcusolverMg.so.11.4.1.48   libnppidei.so.11.8.0.86  libnppitc.so.11         libnvrtc-builtins.so.11.8.89
libcublasLt.so            libcufile_rdma.so.1           libcusolver_lapack_static.a  libnppidei_static.a      libnppitc.so.11.8.0.86  libnvrtc-builtins_static.a
libcublasLt.so.11         libcufile_rdma.so.1.4.0       libcusolver_static.a         libnppif.so              libnppitc_static.a      libnvrtc.so
libcublasLt.so.11.11.3.6  libcufile_rdma_static.a       libcusparse.so               libnppif.so.11           libnpps.so              libnvrtc.so.11.2
libcublasLt_static.a      libcufile_static.a            libcusparse.so.11            libnppif.so.11.8.0.86    libnpps.so.11           libnvrtc.so.11.8.89
libcublas_static.a        libcufilt.a                   libcusparse.so.11.7.5.86     libnppif_static.a        libnpps.so.11.8.0.86    libnvrtc_static.a
libcudadevrt.a            libcuinj64.so                 libcusparse_static.a         libnppig.so              libnpps_static.a        libpcsamplingutil.so
libcudart.so              libcuinj64.so.11.8            liblapack_static.a           libnppig.so.11           libnvToolsExt.so        stubs
libcudart.so.11.0         libcuinj64.so.11.8.87         libmetis_static.a            libnppig.so.11.8.0.86    libnvToolsExt.so.1
libcudart.so.11.8.89      libculibos.a                  libnppc.so                   libnppig_static.a        libnvToolsExt.so.1.0.0
libcudart_static.a        libcupti.so                   libnppc.so.11                libnppim.so              libnvblas.so
libcufft.so               libcupti.so.11.8              libnppc.so.11.8.0.86         libnppim.so.11           libnvblas.so.11
```

Note:
image `cuda:11.8.0-cudnn8-devel-ubuntu22.04`
/usr/local/nvidia doesn;t exist but is what is referenced in lib path
/usr/local/cuda/lib64/lubcudnn.* doesn't exist.

I thought the devel cudnn image was supposed to have all this installed ?
Am I missing something obvious?
