### ISSUE TITLE
nvidia-smi command in container returns "Failed to initialize NVML: Unknown Error" after couple of times

### ISSUE THREAD

**Issue by yuan6711043** [NVIDIA/nvidia-docker#1678]
### 1. Issue or feature description

Nvidia gpu works well upon the container has started, but  when it runs a couple  of times(maybe several days),  gpus mounted by nvidia container runtime becomes invalid.  Command Nvidia-smi returns "Failed to initialize NVML: Unknown Error" in container, while it works well on the  host machine.

<img width="477" alt="image" src="https://user-images.githubusercontent.com/7675988/190060544-2ed90a77-2db4-489e-8229-51b38b76b8db.png">

Nvidia-smi looks well on host,and we can see the training process information through host nvidia-smi command output. If now we stop the training process, it can no longer restart.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/7675988/190060652-5b6285d8-2e21-437e-88b3-d289cec68c99.png">

Referring to the solution from issue https://github.com/NVIDIA/nvidia-docker/issues/1618 . We try to upgrade cgroup to v2 version, but it does not work.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/7675988/190060954-4b87dd9a-97e2-4520-883d-2d8906b49be4.png">

Surprising, we cannot find any devices.list files in the container，which is mentioned in https://github.com/NVIDIA/nvidia-docker/issues/1618 

<img width="578" alt="image" src="https://user-images.githubusercontent.com/7675988/190061119-538ca48d-fd71-480c-95f8-d60edcadd26a.png">

### 2. Steps to reproduce the issue

We find this issue can be reproduced when running "systemctl daemon-reload" on host,but actually we have not run any similar commands in our production environment

![image](https://user-images.githubusercontent.com/7675988/190061334-e1107118-9b32-4016-b95e-6253b2bf40ab.png)

Can anyone give some good ideas for positioning this problem

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

docker: 20.10.7

k8s: v1.22.5

nvidia driver version: 470.103.01

nvidia-container-runtime: 3.8.1-1

containerd: 1.5.5-0ubuntu3~20.04.2

**Comment by mbentley** [comment]
I've noticed the same behavior for some time and thanks for calling out `systemctl daemon-reload` as something that triggers it.  In my case, I have automatic updates enabled in Debian using unattended upgrades and your mention of daemon-reload makes me think that the package updates may be triggering a `daemon-reload` event to occur.  I'm only updating packages from the Debian repos automatically, applying nvidia-docker and 3rd party repo updates manually.

Example from today where I can see the auto updates happening where in this case, telegraf is being updated and then a daemon-reload occurs, or at least that is what I believe I am seeing from `systemd[1]: Reloading.` based on the output when I manually run a `systemctl daemon-reload`:

```
Sep 14 06:46:17 athena systemd[1]: Starting Daily apt upgrade and clean activities...
Sep 14 06:46:50 athena systemd[1]: Stopping The plugin-driven server agent for reporting metrics into InfluxDB...
Sep 14 06:46:52 athena telegraf[6829]: 2022-09-14T10:46:52Z I! [agent] Hang on, flushing any cached metrics before shutdown
Sep 14 06:46:52 athena telegraf[6829]: 2022-09-14T10:46:52Z I! [agent] Stopping running outputs
Sep 14 06:46:52 athena systemd[1]: telegraf.service: Succeeded.
Sep 14 06:46:52 athena systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
Sep 14 06:46:52 athena systemd[1]: telegraf.service: Consumed 14h 46min 50.974s CPU time.
Sep 14 06:46:54 athena systemd[1]: Reloading.
Sep 14 06:46:54 athena systemd[1]: /lib/systemd/system/plymouth-start.service:16: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.
Sep 14 06:46:54 athena systemd[1]: nut-monitor.service: Supervising process 7162 which is not our child. We'll most likely not notice when it exits.
Sep 14 06:46:54 athena systemd[1]: Reloading.
Sep 14 06:46:55 athena systemd[1]: /lib/systemd/system/plymouth-start.service:16: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.
Sep 14 06:46:55 athena systemd[1]: nut-monitor.service: Supervising process 7162 which is not our child. We'll most likely not notice when it exits.
Sep 14 06:46:55 athena systemd[1]: Starting The plugin-driven server agent for reporting metrics into InfluxDB...
Sep 14 06:46:55 athena telegraf[4068755]: 2022-09-14T10:46:55Z W! DeprecationWarning: Option "perdevice" of plugin "inputs.docker" deprecated since version 1.18.0 and will be removed in 2.0.0: use 'perdevice_include' instead
Sep 14 06:46:55 athena telegraf[4068755]: 2022-09-14T10:46:55Z I! Starting Telegraf 1.24.0
Sep 14 06:46:55 athena telegraf[4068755]: 2022-09-14T10:46:55Z I! Available plugins: 222 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
Sep 14 06:46:55 athena telegraf[4068755]: 2022-09-14T10:46:55Z I! Loaded inputs: cpu disk diskio docker exec file ipmi_sensor kernel mem net netstat nvidia_smi processes smart swap system zfs
Sep 14 06:46:55 athena telegraf[4068755]: 2022-09-14T10:46:55Z I! Loaded aggregators:
Sep 14 06:46:55 athena telegraf[4068755]: 2022-09-14T10:46:55Z I! Loaded processors:
Sep 14 06:46:55 athena telegraf[4068755]: 2022-09-14T10:46:55Z I! Loaded outputs: influxdb_v2
Sep 14 06:46:55 athena telegraf[4068755]: 2022-09-14T10:46:55Z I! Tags enabled: host=athena
Sep 14 06:46:55 athena telegraf[4068755]: 2022-09-14T10:46:55Z W! Deprecated inputs: 0 and 1 options
Sep 14 06:46:55 athena telegraf[4068755]: 2022-09-14T10:46:55Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"athena", Flush Interval:10s
Sep 14 06:46:55 athena systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Sep 14 06:47:14 athena systemd[1]: apt-daily-upgrade.service: Succeeded.
Sep 14 06:47:14 athena systemd[1]: Finished Daily apt upgrade and clean activities.
Sep 14 06:47:14 athena systemd[1]: apt-daily-upgrade.service: Consumed 58.400s CPU time.
Sep 14 06:47:29 athena systemd[1]: Starting Cleanup of Temporary Directories...
Sep 14 06:47:29 athena systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
Sep 14 06:47:29 athena systemd[1]: Finished Cleanup of Temporary Directories.
Sep 14 06:50:00 athena systemd[1]: Starting system activity accounting tool...
Sep 14 06:50:00 athena systemd[1]: sysstat-collect.service: Succeeded.
Sep 14 06:50:00 athena systemd[1]: Finished system activity accounting tool.
```

**Comment by elezar** [comment]
Do the packages in the debian repositories include the NVIDIA Drivers?

**Comment by iFede94** [comment]
I'm encountering the same issue. I'm currently testing some solutions proposed in #1650 and #1671 and I will let you know if something works for me.

**Comment by yuan6711043** [comment]
@mbentley thanks for reminding，I will check if there are any auto upgrade packages in our production environments

**Comment by mbentley** [comment]
At least in my case where `telegraf` is a big culprit, I can see that in the post install script it does [call a `systemctl daemon-reload`](https://github.com/influxdata/telegraf/blob/c66ccee46f47717c399ccc0348d17c95d11f477d/scripts/deb/post-install.sh#L16) which matches the behavior I've been seeing.

**Comment by dcarrion87** [comment]
We recently had to solve this for runc interactive issue. E.g.:

- https://github.com/opencontainers/runc/issues/3551#issuecomment-1211427622
- https://github.com/k3s-io/k3s/issues/6064

We only just realised we're hitting this now for GPUs dropping out in containers too.

**Comment by elezar** [comment]
I am closing this as a duplicate of https://github.com/NVIDIA/nvidia-container-toolkit/issues/48 -- a known issue with certain runc / systemd version combinations. Please see the steps to address this there or create a new issue against https://github.com/NVIDIA/nvidia-container-toolkit if you are still having problems.
