### ISSUE TITLE
CUDA driver version is insufficient

### ISSUE THREAD

**Issue by prelution** [NVIDIA/nvidia-docker#180]
I just installed nvidia-docker today with the following link:

[https://github.com/NVIDIA/nvidia-docker#quick-start](url)

I am getting the following error after trying to run deviceQuery in a container:

```
james@Workstation:~$ nvidia-docker run -ti gpu-base-image
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL
```

This is the docker file:

```
FROM nvidia/cuda:7.5-cudnn5-devel

# Make and Run the CUDA deviceQuery sample
RUN apt-get update && apt-get install -y --no-install-recommends \
        cuda-samples-$CUDA_PKG_VERSION && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /usr/local/cuda/samples/1_Utilities/deviceQuery
RUN make
CMD ./deviceQuery
```

I checked the version and it is the same as the host:

```
james@Workstation:~$ nvidia-docker run -ti gpu-base-image bash
root@bcfdccba90b2:/proc/driver/nvidia# cat version 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.63  Sat Nov  7 21:25:42 PST 2015
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
```

Another note I should point out is that there is no nvidia-smi that I can call in the container:

```
root@bcfdccba90b2:/proc/driver/nvidia# nvidia-smi
bash: nvidia-smi: command not found

or

james@Workstation:~$ nvidia-docker run --rm -ti nvidia/cuda:7.5-cudnn5-devel nvidia-smi
docker: Error response from daemon: Container command 'nvidia-smi' not found or does not exist..
```

Also I was not able to run the nvidia/cuda:7.5-cudnn5-devel until I made the directory: /var/lib/nvidia-docker/volumes/nvidia_driver/352.63/lib64 becuase I was getting the following error in the log file:

```
/usr/bin/nvidia-docker-plugin | 2016/08/25 14:03:25 Error: link /usr/src/gdk/nvml/lib/libnvidia-ml.so.1 /var/lib/nvidia-docker/volumes/nvidia_driver/352.63/lib64/libnvidia-ml.so.1: file exists
```

I can't fathom what I am doing wrong...

**Comment by flx42** [comment]
You shouldn't start twiddling with the volume folder directly, that's dangerous :)
I advise you start again from a fresh install, purge nvidia-docker:
```
apt-get purge nvidia-docker
rm -rf /var/lib/nvidia-docker
```
And then reinstall it.

Now, the error you have with `libnvidia-ml.so.1` could be because you have the GDK (GPU Deployment Kit) installed. What's the output of `ldconfig -p | grep libnvidia-ml` for you?

**Comment by flx42** [comment]
Also, make sure `nvidia-smi` works fine on the host.

**Comment by prelution** [comment]
The nvidia-smi works just fine on the host machine.  It appears that the nvidia-smi is missing in the docker container.  

I do have GDK installed.  It is need for other projects I am working on.  I beleive the error is creating the link in the /var/lib/nvidia-docker/volumes/nvidia_driver/352.63/lib64.  When the volume was being created was when I got the error and the directories 352.63/lib64 was not in the nvidia_driver directory.  Once added the problem went away.

Here is the output you asked for:

```
james@Workstation:~$ ldconfig -p | grep libnvidia-ml
	libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/nvidia-352/libnvidia-ml.so.1
	libnvidia-ml.so.1 (libc6,x86-64) => /usr/src/gdk/nvml/lib/libnvidia-ml.so.1
	libnvidia-ml.so.1 (libc6) => /usr/lib32/nvidia-352/libnvidia-ml.so.1
	libnvidia-ml.so (libc6,x86-64) => /usr/lib/nvidia-352/libnvidia-ml.so
	libnvidia-ml.so (libc6,x86-64) => /usr/src/gdk/nvml/lib/libnvidia-ml.so
	libnvidia-ml.so (libc6) => /usr/lib32/nvidia-352/libnvidia-ml.so
```

I will try to purge and reinstall.  I will let you know what happens.

**Comment by prelution** [comment]
Ok, I have purged and reinstalled a couple of times and have done a couple of reboots.  I had to start the plugin to get past the following error:

```
docker: Error response from daemon: create nvidia_driver_352.63: create nvidia_driver_352.63: Error looking up volume plugin nvidia-docker: plugin not found.
```

Here is where I am now:

```
james@Workstation:~$ sudo -b nohup nvidia-docker-plugin
james@Workstation:~$ nohup: ignoring input and appending output to ‘nohup.out’
^C
james@Workstation:~$ nvidia-docker run --rm nvidia/cuda:7.5 nvidia-smi
docker: Error response from daemon: create nvidia_driver_352.63: VolumeDriver.Create: internal error, check logs for details.
See 'docker run --help'.
```

There new thing that is weird is that the error about the link that is had before in the log file is not there.  It appears that nothing is getting appended.  There is a new error in the file but the time stamp does not corresponds to rebooting the system I believe.  Here is the whole log file:

```
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:34:50 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:34:50 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:34:50 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:34:51 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:34:51 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:34:51 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:34:58 Successfully terminated
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:36:12 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:36:12 Error: Could not load UVM kernel module
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:36:12 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:36:12 Error: Could not load UVM kernel module
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:36:12 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:36:12 Error: Could not load UVM kernel module
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:36:12 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:36:12 Error: Could not load UVM kernel module
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:36:12 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:36:12 Error: Could not load UVM kernel module
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:36:12 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/08/26 11:36:12 Error: Could not load UVM kernel module
```

**Comment by 3XX0** [comment]
`/usr/src/gdk/nvml/lib/libnvidia-ml.so.1` should not be in your ldcache.
This library is a stub library and is only useful for development purposes.
Remove the path from your `/etc/ld.so.conf` or `/etc/ld.so.conf.d` and rebuild the cache with `ldconfig`

Your second error is different and probably due to your driver installation. Check that `nvidia-modprobe` is present on your machine and that you can load UVM with it (`nvidia-modprobe -u -c=0)

**Comment by prelution** [comment]
Ok, I now have things working.  I think the main issues were that I did not have nvidia-modprobe on my machine and the ldcache during installation.  I do want to make another note, I was having permission issues when I tried: 

`nvidia-docker run --rm nvidia/cuda:7.5 nvidia-smi`

Here is the log:

```
/usr/bin/nvidia-docker-plugin | 2016/08/26 15:30:02 Error: mkdir /var/lib/nvidia-docker/volumes/nvidia_driver/352.63: permission denied
```

Once I chmod the directory to 777 I was able to run the command:

```
james@Workstation:~$ nvidia-docker run --rm nvidia/cuda:7.5 nvidia-smi
Fri Aug 26 23:07:59 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.63     Driver Version: 352.63         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 650 Ti  Off  | 0000:05:00.0     N/A |                  N/A |
| 30%   39C    P0    N/A /  N/A |    304MiB /  1023MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 780 Ti  Off  | 0000:41:00.0     N/A |                  N/A |
| 34%   29C    P8    N/A /  N/A |     11MiB /  3071MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
|    1                  Not Supported                                         |
+-----------------------------------------------------------------------------+
```

**Comment by 3XX0** [comment]
The permission problem is probably because you started the plugin manually as root (i.e. `sudo -b nohup nvidia-docker-plugin`) whereas with the package install the plugin is running as `nvidia-docker`.

If you want to start fresh, purge the package and make sure `/var/lib/nvidia-docker` is removed then reinstall the package. It should now have the proper permissions
