### ISSUE TITLE
Building Ubuntu14.04 cuda 7.5 cudnn5 devel image fails

### ISSUE THREAD

**Issue by bpmweel** [NVIDIA/nvidia-docker#298]
When building the ubuntu14.04 cuda 7.5 cudnn5 devel image I get the following error:

```
The following packages have unmet dependencies:
 libcudnn5-dev : Depends: libcudnn5 (= 5.1.3-1+cuda7.5) but 5.1.10-1+cuda8.0 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Changing the apt-get install command in Dockerfile to the following fixes the issue.
```
RUN apt-get update && apt-get install -y --no-install-recommends \
            libcudnn5=5.1.3-1+cuda7.5 \                                                                                                                               
            libcudnn5-dev=5.1.3-1+cuda7.5 && \
     rm -rf /var/lib/apt/lists/*
```

**Comment by flx42** [comment]
You are building the images from sources, why aren't you using our prebuilt images on the DockerHub? 

The Dockerfiles in this repo are being deprecated, we are in the process of splitting the runtime (`nvidia-docker`) and the images. The official CUDA/cuDNN/caffe/DIGITS are now on GitLab and we use their CI system to automate build and push to DockerHub:
https://gitlab.com/nvidia/cuda/pipelines
However, the GitLab repo doesn't have a makefile, so it's a slightly challenging to build everything yourself. Thus, I'm interested to know why our official images are not working for you.

This issue is solved on GitLab, I now use the latest cuDNN. 
Going forward, I'm either going to keep the Dockerfiles in sync for a little while longer (if you have a good use case), or I'm going to remove all the Dockerfiles from this repo and GitLab will be the only place to get them.

**Comment by bpmweel** [comment]
@flx42 I feel a little silly.

I had searched for the prebuilt images on Dockerhub, but didn't find them. Perhaps that was because they are not labeled as "official" I don't know. I will switch to the prebuilt ones. thank you.

**Comment by flx42** [comment]
Ah, no problem. They are indeed not **official** in the DockerHub sense, they are official because they are published by NVIDIA. But soon using the new Docker Store will make the distinction more blurry anyway.
