### ISSUE TITLE
libcuda.so building issues

### ISSUE THREAD

**Issue by nmiculinic** [NVIDIA/nvidia-docker#374]
I get import error libcuda.so.1 not found while building following dockerfile https://pastebin.com/3w0zMPhj

I googled and read all I could read yet I couldn't debug a problem. A few weeks ago it was working like a charm, but today after setting --no-cache option during building it all fell to pieces. 

Furthermore I tried following image with similar results: 
https://pastebin.com/Et4QhY2a

**Comment by flx42** [comment]
I haven't looked at your Dockerfile, but if you want to link against `libcuda`, you must use the `libcuda.so` stub from `/usr/local/cuda/lib64/stubs`.
If you are trying to execute GPU code from a Dockerfile, it won't work.

**Comment by nmiculinic** [comment]
It worked just fine 4ish weeks ago; same config actually. I'm using devel images in dockerfiles.

I remember somewhere readings about stubs added to library path in devel, will update/edit in the morning. And that's I shouldn't have to link manually.

Nevertheless I tried manually symlinking and it didn't work. Could you please recommend me how should I use that? Build system underneath is cmake for warp-ctc module(where it fails), tensorflow is prebuilt.

**Comment by flx42** [comment]
What are you trying to manually symlink?
What's the error message?

**Comment by 3XX0** [comment]
@nmiculinic did you find the issue?

**Comment by nmiculinic** [comment]
I used lower tensorflow version which didn't suffer this problem since my priority was getting working system first. 

I suspect there's some change in tensorflow versions which affect warp-ctc installation procedure, but I haven't debugged further for now.

**Comment by nmiculinic** [comment]
Ok I solved it.

I added this two lines and modified problematic one:
```
RUN ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1
RUN LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/:$LD_LIBRARY_PATH python3 setup.py install 
RUN rm /usr/local/cuda/lib64/stubs/libcuda.so.1
```

and that solved the issue. I guess tensorflow changed from implicit libcuda.so to explicit libcuda.so.1 dependency, but I tried without explicit LD_LIBRARY_PATH and it fails. I guess that's needed.
