### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by panda87** [NVIDIA/nvidia-docker#400]
Hi

I encountered this error: `Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version` during my app processing.

Machine details:
GCE with GPU Tesla K80
OS: Ubuntu 14.04
The Driver installed is: NVIDIA-Linux-x86_64-375.66.run with nvidia-docker nvidia-docker_1.0.1.

Im using the following docker image, based on `nvidia/cuda:7.0-cudnn4-devel-ubuntu14.04`NVIDIA official Docker image 
[kaixhin/cuda-caffe:7.0](https://github.com/Kaixhin/dockerfiles/tree/master/cuda-caffe/cuda_v7.0)

On top of that I compiled OpenCV 3.0.0

`$nvidia-smi / run --rm nvidia/cuda:7.0-runtime nvidia-smi`
```
Thu Jun 15 19:24:53 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:00:04.0     Off |                    0 |
| N/A   55C    P8    31W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

`$ldconfig -p | grep cuda`
```
	libicudata.so.52 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libicudata.so.52
	libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
	libcuda.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so
```

`$nvidia-docker run --rm device`
```
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "Tesla K80"
  CUDA Driver Version / Runtime Version          8.0 / 8.0
  CUDA Capability Major/Minor version number:    3.7
  Total amount of global memory:                 11440 MBytes (11995578368 bytes)
  (13) Multiprocessors, (192) CUDA Cores/MP:     2496 CUDA Cores
  GPU Max Clock rate:                            824 MHz (0.82 GHz)
  Memory Clock rate:                             2505 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 1572864 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Enabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 0 / 4
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 8.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = Tesla K80
Result = PASS
```

Can you pls help me solve this issue?
D.

**Comment by flx42** [comment]
@panda87 did you solve the problem?

**Comment by panda87** [comment]
Yes
I didn't know that I need to install the driver also in the docker container, once I did that, it start work

**Comment by flx42** [comment]
@panda87 No, you don't need to do that when using `nvidia-docker run`.

**Comment by panda87** [comment]
I tried without this almost a week, of course with `nvidia-docker run`
But only when I installed that in the docker I got that

**Comment by flx42** [comment]
You should try the `bvlc/caffe` or `nvidia/caffe` images instead of the old one you're using.

**Comment by panda87** [comment]
I looked at `bvlc/caffe`, the reason is didn't use `nvidia/caffe` is because of caffe compatible issues and I didn't want to put myself into, but thaks

**Comment by panda87** [comment]
In addition, Im using ubuntu14 with cuda7.0 and cudnn4. All the examples above are for cuda8.0 with ubuntu 16.04

**Comment by flx42** [comment]
What's wrong with cuda 8.0 and ubuntu 16.04 of they are inside a container?

**Comment by panda87** [comment]
Nothing, just our app is working with cuda 7.0 and cudnn4

**Comment by xuyifeng-nwpu** [comment]
@flx42     Must the version of  cuda in the host  and docker's container  be equal ?

Must the version of  nvidia's driver in the host  and docker's container  be equal ?

**Comment by zhangkai1234** [comment]
this means you nvidia driver is not fit ,for ex: my nvidia driver is GTX-1050,the version number is 390,but if you install a driver nvidia-384,you will get this error: CUDA driver version is insufficient for CUDA runtime version. the way to slove it is to install the right version of nvidia driver.

**Comment by serg06** [comment]
I was able to fix this issue by running the container with `--gpus all`.
