### ISSUE TITLE
cuda-memcheck and nvprof unable to collect debugging information inside container

### ISSUE THREAD

**Issue by MilesCranmer** [NVIDIA/nvidia-docker#454]
Hi,

First off, this is a great project. I use it every day for development and it has saved me quite a bit of time. Thanks for creating it.

Now, my issue:

When I run:
```
cuda-memcheck --leak-check full  $RTS/bin/rts_sim cuwarp.in
```
to check for memory leaks (because the GPU is running out of memory), the output is:
```
========= CUDA-MEMCHECK
...
...
...
CUDA Error in file 'uv_grid_t_cuda.cu' on line 83 : out of memory.
========= Internal error (7)
========= No CUDA-MEMCHECK results found
```
Furthermore, I tried to run `nvprof` on this:
```
nvprof --profile-from-start off $RTS/bin/rts_sim cuwarp.in
```
(after manually adding a call to `cudaProfilerStart()` before the leaking code), and I get
```
==630== NVPROF is profiling process 630, command: /workspace/rts/bin/rts_sim cuwarp.in
...
...
...
CUDA Error in file 'gridder_spheroid.cu' on line 204 : out of memory.
==630== Profiling application: /workspace/rts/bin/rts_sim cuwarp.in
==630== Profiling result:
No kernels were profiled.

==630== API calls:
No API activities were profiled.
======== Error: Application returned non-zero code 1
```

I am running this inside an nvidia/cuda container, started with:
```
nvidia-docker run -it --name minion -v $HOME:/workspace -v /var/run/docker.sock:/var/run
/docker.sock -v /usr/bin/docker:/usr/bin/docker --security-opt seccomp=unconfined rts-dev
```

The `--security-opt seccomp=unconfined` call is necessary to get `gdb` and `cuda-gdb` working inside the container.

To add, when I cut the loop in my program short to prevent an out of memory error, I also observe `cuda-memcheck` not producing an output.

Do you have any suggestions for where I could look next? This SO issue (unanswered) could be related: https://stackoverflow.com/questions/44932202/cuda-memcheck-internal-error-7

Thanks in advance,
Miles

**Comment by MilesCranmer** [comment]
More information:

- Hardware
    - AWS p2.xlarge
        - Tesla K80 GPU
- Software
    - ubuntu 16.04 (host machine)
    - Cuda compilation tools v8.0.61
    - Base container: `nvidia/cuda` (image from 6 weeks ago)

**Comment by flx42** [comment]
Inside the container, do you have the device `/dev/nvidia-uvm-tools`?

**Comment by MilesCranmer** [comment]
I see it there:
```
➜  ls -lath /dev/nvidia-uvm-tools
crw-rw-rw- 1 root root 247, 1 Aug 17 15:24 /dev/nvidia-uvm-tools
```

**Comment by flx42** [comment]
I haven't used `cuda-memcheck` or `nvprof` that much, but it worked for me inside containers.
Another test would be to run the container with `--privileged`, and check if it solves the problem.
If it's not helping, using `strace -f cuda-memcheck [...]` might help find where the issue comes from.

**Comment by MilesCranmer** [comment]
The `--privileged` flag got it, thanks!
I am now able to see the output of cuda-memcheck. No leaks were found, but I presume that is the same as would be found outside of docker. (Because it does show the full backtrace of my memory allocation error). Before it started working, cuda-memcheck finished at normal execution speed (suspicious), but now it runs the program at ~20 times slower (expected).

Thanks for your help,
Miles

**Comment by 3XX0** [comment]
@MilesCranmer Can you provide the output of `strace -f cuda-memcheck [...]` without the `--privileged`? It would be useful to see what is going on.

**Comment by MilesCranmer** [comment]
Hi @3XX0, no problem. The full output is 180 MB, so are there any specific regexp's you would like me to  extract from it? I won't be able to upload the full file until tomorrow (very slow upload speed).

Until then, here's the first and last 1000 lines:

[first_1000.txt](https://github.com/NVIDIA/nvidia-docker/files/1240433/first_1000.txt)
[last_1000.txt](https://github.com/NVIDIA/nvidia-docker/files/1240434/last_1000.txt)

**Comment by 3XX0** [comment]
Thanks! As expected, that's a problem on our side.
Can you confirm that it works with `--ipc=host` instead of `--privileged`?

**Comment by MilesCranmer** [comment]
No problem.
I just tried the `--ipc=host` flag and it produces the same error as I saw initially.

Here is the strace output:

[first_1000_ipc_host.txt](https://github.com/NVIDIA/nvidia-docker/files/1240560/first_1000_ipc_host.txt)
[last_1000_ipc_host.txt](https://github.com/NVIDIA/nvidia-docker/files/1240563/last_1000_ipc_host.txt)

**Comment by 3XX0** [comment]
What about `strace -f cuda-memcheck [...] 2>&1 | grep '= -1'`?
Also, can you share the kernel in question or a simple example that could reproduce the issue?

**Comment by MilesCranmer** [comment]
Here is the result of the only `-1` results (from my initial run without --ipc=host or --privileged): [only_negative_1.txt](https://github.com/NVIDIA/nvidia-docker/files/1243003/only_negative_1.txt)

There isn't really a specific kernel I'm debugging—it's a 70k-line project that I've started to look at (closed source unfortunately) and the memory leak could be hiding almost anywhere. It's mostly thrust calls. If you are interested in a specific part of the code, I can probably get permission to post.

I will try memcheck again with some of the CUDA example files later today, and post the results. Any settings that you would like me to test them with?

**Comment by 3XX0** [comment]
Thanks, I don't think we will need the code, it's probably caused by nvidia-docker or your driver install.
Are you doing anything specific with Docker, user namespaces maybe?
From your example, it seems that your are running DinD.

Also, can you give me the output of
- `capsh --print` and `cat /sys/fs/cgroup/devices/devices.list` from within the container
- `getfattr -d -m ".*" /dev/nvidia*` from the host.

**Comment by MilesCranmer** [comment]
I don't recall doing anything of that nature with the Docker, but I wonder if the DinD effect you observed is due to AWS EC2's virtualization for my underlying instance?

```
(container)> capsh --print
Current: = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+eip
Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=0(root)
gid=0(root)
groups=
(container)>
```

```
(container)> cat /sys/fs/cgroup/devices/devices.list
c 1:5 rwm
c 1:3 rwm
c 1:9 rwm
c 1:8 rwm
c 5:0 rwm
c 5:1 rwm
c 195:255 rwm
c 247:0 rwm
c 195:0 rwm
c *:* m
b *:* m
c 1:7 rwm
c 136:* rwm
c 5:2 rwm
c 10:200 rwm
(container)>
```

```
(host)> getfattr -d -m '.*' /dev/nvidia*
(host)>
```
(no output)

strace of getfattr: http://termbin.com/wlii

**Comment by MilesCranmer** [comment]
Also, I am curious: how could you tell it is likely DinD? I'm interested in learning how you interpret the strace for these sorts of conclusions.

**Comment by 3XX0** [comment]
You are missing permissions on the UVM devices, this is likely the issue. I'm not sure how this could have happened though.
What is the output of `curl -s http://localhost:3476/docker/cli\?dev=0`?`

**Comment by MilesCranmer** [comment]
Output (host):
`--volume-driver=nvidia-docker --volume=nvidia_driver_375.66:/usr/local/nvidia:ro --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia0`

**Comment by 3XX0** [comment]
Can you double check that you are running the latest version of nvidia-docker?
Also check on the host if `/dev/nvidia-uvm-tools` is here and try doing `sudo nvidia-modprobe -u -c=0` see if it fixes the issue

**Comment by 3XX0** [comment]
@MilesCranmer fixed?

**Comment by linrio** [comment]
@flx42 And how to use the `nvprof` in nvidia-docker container ?

**Comment by linrio** [comment]
@MilesCranmer @3XX0  How to run the `cuda-memcheck` or `nvprof` in container? I try to run `nvprof` in 
nvidia-docker container however it throws error:
First:
linlf@linlf:~/project/$ sudo nvidia-docker run --privileged --security-opt seccomp=unconfined --device=/dev/nvidia-uvm-tools -i
t -v `pwd`:/paddle / /bin/bash

Then:

```
root@247c5efebbc5:/# nvprof
bash: nvprof: command not found
```

**Comment by leimao** [comment]
I found cuda-memcheck cannot detect the memories that have not been garbage-collected inside the Docker container. That is to say, if I delete a line of `cudaFree` from a CUDA program, cuda-memcheck will still not raise an error or warning inside the Docker container for that program.
