### ISSUE TITLE
Can not run nvidia-docker for facebook detectron installation

### ISSUE THREAD

**Issue by gecong** [NVIDIA/nvidia-docker#663]
I am in the process of installing facebook Detectron. I ran the following comment to install from docker:

nvidia-docker run --rm -it detectron:c2-cuda9-cudnn7

I got the following error:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused "process_linux.go:385: running prestart hook 1 caused \"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=13668 /var/lib/docker/aufs/mnt/df276136eced8bb014e4d7f28fa6dd47d837cc6c11b461b3eb67a1863904cba8]\\nnvidia-container-cli: initialization error: cuda error: unknown error\\n\""": unknown.

Could anyone help?

**Comment by flx42** [comment]
Please provide the information described in our standard issue template.

**Comment by zbl-96** [comment]
same issue.if you solve please @ me

**Comment by flx42** [comment]
@zbl-96 well, you need to help us troubleshoot the issue by posting more information. 
here's the issue template: https://github.com/NVIDIA/nvidia-docker/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by flx42** [comment]
@deeprun @gecong @zbl-96 please provide more information, or we'll close this issue.

**Comment by fuankarion** [comment]
I have the very same issue, 

**Kernel Version**
Linux bcv002 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Driver Version**   
387.26

**Docker Version**
Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6

**NVIDIA packages version**
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version          Architecture     Description
+++-=======================-================-================-===================================================
ii  libnvidia-container-too 1.0.0~beta.1-1   amd64            NVIDIA container runtime library (command-line tool
ii  libnvidia-container1:am 1.0.0~beta.1-1   amd64            NVIDIA container runtime library
rc  nvidia-361              361.62-0ubuntu1  amd64            NVIDIA binary driver - version 361.62
rc  nvidia-367              375.39-0ubuntu0. amd64            Transitional package for nvidia-375
rc  nvidia-375              375.88-0ubuntu1  amd64            NVIDIA binary driver - version 375.88
rc  nvidia-384              384.90-0ubuntu0. amd64            NVIDIA binary driver - version 384.90
ii  nvidia-387              387.26-0ubuntu1  amd64            NVIDIA binary driver - version 387.26
ii  nvidia-387-dev          387.26-0ubuntu1  amd64            NVIDIA binary Xorg driver development files
ii  nvidia-container-runtim 2.0.0+docker17.1 amd64            NVIDIA container runtime
ii  nvidia-container-runtim 1.3.0-1          amd64            NVIDIA container runtime hook
ii  nvidia-cuda-dev         7.5.18-0ubuntu1  amd64            NVIDIA CUDA development files
ii  nvidia-cuda-doc         7.5.18-0ubuntu1  all              NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb         7.5.18-0ubuntu1  amd64            NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit     7.5.18-0ubuntu1  amd64            NVIDIA CUDA development toolkit
un  nvidia-current          <none>           <none>           (no description available)
un  nvidia-docker           <none>           <none>           (no description available)
ii  nvidia-docker2          2.0.3+docker17.1 all              nvidia-docker CLI wrapper
un  nvidia-driver           <none>           <none>           (no description available)
un  nvidia-driver-binary    <none>           <none>           (no description available)
un  nvidia-legacy-340xx-vdp <none>           <none>           (no description available)
un  nvidia-libopencl1       <none>           <none>           (no description available)
un  nvidia-libopencl1-361   <none>           <none>           (no description available)
un  nvidia-libopencl1-375   <none>           <none>           (no description available)
un  nvidia-libopencl1-384   <none>           <none>           (no description available)
un  nvidia-libopencl1-387   <none>           <none>           (no description available)
un  nvidia-libopencl1-dev   <none>           <none>           (no description available)
ii  nvidia-machine-learning 1.0.0-1          amd64            nvidia-machine-learning repository configuration fi
ii  nvidia-modprobe         390.30-0ubuntu1  amd64            Load the NVIDIA kernel driver and create device fil
ii  nvidia-opencl-dev:amd64 7.5.18-0ubuntu1  amd64            NVIDIA OpenCL development files
un  nvidia-opencl-icd       <none>           <none>           (no description available)
rc  nvidia-opencl-icd-361   361.62-0ubuntu1  amd64            NVIDIA OpenCL ICD
rc  nvidia-opencl-icd-367   375.39-0ubuntu0. amd64            Transitional package for nvidia-opencl-icd-375
rc  nvidia-opencl-icd-375   375.88-0ubuntu1  amd64            NVIDIA OpenCL ICD
rc  nvidia-opencl-icd-384   384.90-0ubuntu0. amd64            NVIDIA OpenCL ICD
ii  nvidia-opencl-icd-387   387.26-0ubuntu1  amd64            NVIDIA OpenCL ICD
un  nvidia-persistenced     <none>           <none>           (no description available)
ii  nvidia-prime            0.8.2            amd64            Tools to enable NVIDIA's Prime
ii  nvidia-profiler         7.5.18-0ubuntu1  amd64            NVIDIA Profiler for CUDA and OpenCL
ii  nvidia-settings         390.30-0ubuntu1  amd64            Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binary  <none>           <none>           (no description available)
un  nvidia-smi              <none>           <none>           (no description available)
un  nvidia-vdpau-driver     <none>           <none>           (no description available)
ii  nvidia-visual-profiler  7.5.18-0ubuntu1  amd64            NVIDIA Visual Profiler for CUDA and OpenCL

**nvidia-container-cli -V**
build date: 2018-03-06T01:53+00:00
build revision: be797da00b156493e80f1ae6f38d69f23c932554
build compiler: gcc-5 5.4.0 20160609
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

**command**
docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi

**Comment by fold0** [comment]
I had this error on a fresh install of debian testing. Solved by installing nvidia-cuda-toolkit. I guess some deps are missing in the packages

**Comment by flx42** [comment]
@fold0 our packages don't depend on the NVIDIA driver, since there are multiple ways to install them.

@fuankarion does CUDA work on the host for you?

**Comment by fuankarion** [comment]
@flx42 it does version 9.1 with CUDNN.

**Comment by fold0** [comment]
>our packages don't depend on the NVIDIA driver, since there are multiple ways to install them.

I had of course installed nvidia-driver package first thing. The fact that it alone wasn't enough and some other packages were needed that got pulled by cuda toolkit was not obvious. I'd certainly appreciate a better error message than a cryptic "initialization error: cuda error: unknown error" here
