### ISSUE TITLE
Fails with CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by vardhanv** [NVIDIA/nvidia-docker#747]
What am i missing ?

My host (18.04) is configured as follows:
sudo apt-get -y install nvidia-driver-396 nvidia-modprobe nvidia-docker2

My container is built from:
FROM nvidia/cuda:9.2-cudnn7-devel-ubuntu18.04

I am using a K80 GPU (on AWS).

I get the following core dump:
Setting up Caffe in GPU mode with ID: 0
F0524 09:04:15.975416  9945 common.cpp:152] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
    @     0x7f32429400cd  google::LogMessage::Fail()
    @     0x7f3242941f33  google::LogMessage::SendToLog()
    @     0x7f324293fc28  google::LogMessage::Flush()
    @     0x7f3242942999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3242e57c72  caffe::Caffe::SetDevice()
    @     0x55e94c57fde4  (unknown)
    @     0x55e94c5809d4  (unknown)
    @     0x55e94c579db6  (unknown)
    @     0x7f32414f9b97  __libc_start_main
    @     0x55e94c57a8ca  (unknown)

// In the HOST

$ nvidia-smi --query-gpu=gpu_name,gpu_bus_id,vbios_version --format=csv
name, pci.bus_id, vbios_version
Tesla K80, 00000000:00:1E.0, 80.21.1F.00.01

$  lspci -v | grep -i nvidia
00:1e.0 3D controller: NVIDIA Corporation GK210GL [Tesla K80] (rev a1)
	Subsystem: NVIDIA Corporation GK210GL [Tesla K80]
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nvidia_drm, nvidia

$ cat /proc/driver/nvidia/version 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  396.24  Thu Apr 26 00:10:09 PDT 2018
GCC version:  gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)

**Comment by flx42** [comment]
How did you run the container? Is `nvidia-smi` working inside the container?

**Comment by vardhanv** [comment]
nvidia-smi was working. I rebuilt everything, and it seems to be working now. Will close and repopen if required. thanks for being so responsive.

**Comment by vardhanv** [comment]
nvidia-smi was working in the container, and after a while it seems to have stopped. 

Not sure what is going on. I doing some general builds (caffe etc), but suddenly the earlier error returned (CUDA driver version is insufficient). I killed the container, and restarted it.. but it is not finding nvidia-smi

**Comment by flx42** [comment]
When it doesn't work, what is your `docker run` line?
Also, what is the output of `findmnt` inside the container?
