### ISSUE TITLE
How to get GPU architecture at build stage?

### ISSUE THREAD

**Issue by Jasonsey** [NVIDIA/nvidia-docker#797]
I was compiling my project based on [sceneReco](git@github.com:bear63/sceneReco.git) , which is based on Caffe by Dockerfile. And I had successfully build the image and started the container. Everything seemed to be OK...but when I tryed to use my project to recognize a image, I got the following Message, and the container exited:

```Shell
Check failed: error == cudaSuccess (8 vs. 0) no kernel image is available for execution on the device
```

Then when I checked the compiling logs, I found the message. My GPU model is GTX1080Ti, and the GPU arch(s) should be sm_61:

```Shell
...
-- CUDA detected: 8.0
-- Found cuDNN (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_20 sm_21 sm_30 sm_35 sm_50
-- OpenCV found (/usr/share/OpenCV)
...
-- ******************* Caffe Configuration Summary *******************
...
--
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_20 sm_21 sm_30 sm_35 sm_50
--   cuDNN             :   Yes
...
```

Then I searched Google for this, and I found the issue #597, which like the similar problem I met. Then I tryed the solution, but Unfortunately, I got the following message:

```Shell
CMake Warning:
  Manually-specified variables were not used by the project:
    CUDA_ARCH_BIN
```

And the following Error, then project exit when I tryed to recognize a image again:

```Shell
Check failed: error == cudaSuccess (8 vs. 0) no kernel image is available for execution on the device
```

And the compiling logs:

```Shell
...
-- Added CUDA NVCC flags for: sm_20 sm_21 sm_30 sm_35 sm_50
...
--   GPU arch(s)       :   sm_20 sm_21 sm_30 sm_35 sm_50
...
```

Then I tryed to build the image Step-by-Step interactively inside the container. You guess what? I got the following message:

```Shell
...
-- Added CUDA NVCC flags for: sm_61
...
--   GPU arch(s)       :   sm_61
...
```

I was surprised and I immediately start my project and the program run well ! But I still have to build my project by the Dockerfile without entering the container then build myself. Uhh...I guess maybe the intermediate container created while building a image did not have a suitable Cuda environment ?

Ok. I try the following steps, and it works:
1. not build caffe while building the images
2. build caffe in Dockerfile's `CMD` command

So Here is the old Dockerfile:

```Dockerfile
FROM nvidia/cuda:8.0-devel-ubuntu16.04
MAINTAINER Max <***>


ENV TZ=Asia/Shanghai
ENV APP_ROOT=/opt/code

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
WORKDIR $APP_ROOT/

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        wget \
        zip \
        unzip \
        libatlas-base-dev \
        libboost-all-dev \
        libgflags-dev \
        libgoogle-glog-dev \
        libhdf5-serial-dev \
        libleveldb-dev \
        liblmdb-dev \
        libopencv-dev \
        libprotobuf-dev \
        libsnappy-dev \
        protobuf-compiler \
        python-dev \
        python-numpy \
        python-setuptools \
        python-scipy \
        python-pip \
        thrift-compiler \
        vim && \
    rm -rf /var/lib/apt/lists/*
ADD dependency/pip-10.0.1.tar /
RUN cd /pip-10.0.1 && python setup.py install && cd .. && rm -r pip-10.0.1
# Only the v3.0.8 is the filtable version
ADD dependency/cudnn-7.0-linux-x64-v3.0.8-prod.tar /
RUN cp -P /cuda/include/cudnn.h /usr/include/
RUN cp -P /cuda/lib64/libcudnn* /usr/lib/x86_64-linux-gnu/ && rm -r /cuda
# Optional
RUN git clone --depth=1 https://gitee.com/Nvidia/nccl.git
RUN cd nccl && make -j"$(nproc)" install && cd .. && rm -rf nccl
# Python dependency
COPY requirements.txt $APP_ROOT/
RUN pip install --no-cache-dir --trusted-host mirrors.aliyun.com -i http://mirrors.aliyun.com/pypi/simple/ -q -r requirements.txt

COPY . $APP_ROOT/
RUN find . -name "*.pyc" -delete

# Config CTPN
WORKDIR $APP_ROOT/CTPN/
RUN cd caffe && cp Makefile.config.example Makefile.config && mkdir build
RUN make caffe

# Set the environment variables so that the paths are correctly configured
ENV PYCAFFE_ROOT=$APP_ROOT/CTPN/caffe/python
ENV CTPN_ROOT=$APP_ROOT/CTPN/src
ENV PYTHONPATH=$PYCAFFE_ROOT:$CTPN_ROOT:$PYTHONPATH
ENV PATH=$APP_ROOT/CTPN/caffe/build/tools:$PYCAFFE_ROOT:$PATH
RUN echo "$APP_ROOT/CTPN/caffe/build/lib" >> /etc/ld.so.conf.d/caffe.conf && ldconfig

# Config CRNN
WORKDIR $APP_ROOT/
RUN thrift -r -gen py -out gen_thrift interface.thrift

CMD python server_thrift.py
```

And the new Dockerfile:

```Dockerfile
FROM nvidia/cuda:8.0-devel-ubuntu16.04
MAINTAINER Max <***>

ENV TZ=Asia/Shanghai
ENV APP_ROOT=/opt/code

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
WORKDIR $APP_ROOT/

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        wget \
        zip \
        unzip \
        libatlas-base-dev \
        libboost-all-dev \
        libgflags-dev \
        libgoogle-glog-dev \
        libhdf5-serial-dev \
        libleveldb-dev \
        liblmdb-dev \
        libopencv-dev \
        libprotobuf-dev \
        libsnappy-dev \
        protobuf-compiler \
        python-dev \
        python-numpy \
        python-setuptools \
        python-scipy \
        python-pip \
        thrift-compiler \
        vim && \
    rm -rf /var/lib/apt/lists/*
ADD dependency/pip-10.0.1.tar /
RUN cd /pip-10.0.1 && python setup.py install && cd .. && rm -r pip-10.0.1
# Only the v3.0.8 is the filtable version
ADD dependency/cudnn-7.0-linux-x64-v3.0.8-prod.tar /
RUN cp -P /cuda/include/cudnn.h /usr/include/
RUN cp -P /cuda/lib64/libcudnn* /usr/lib/x86_64-linux-gnu/ && rm -r /cuda
# Optional
RUN git clone --depth=1 https://gitee.com/Nvidia/nccl.git
RUN cd nccl && make -j"$(nproc)" install && cd .. && rm -rf nccl
# Python dependency
COPY requirements.txt $APP_ROOT/
RUN pip install --no-cache-dir --trusted-host mirrors.aliyun.com -i http://mirrors.aliyun.com/pypi/simple/ -q -r requirements.txt

COPY . $APP_ROOT/
RUN find . -name "*.pyc" -delete

# Config CTPN
WORKDIR $APP_ROOT/CTPN/
RUN cd caffe && cp Makefile.config.example Makefile.config && mkdir build
#RUN make caffe

# Set the environment variables so that the paths are correctly configured
ENV PYCAFFE_ROOT=$APP_ROOT/CTPN/caffe/python
ENV CTPN_ROOT=$APP_ROOT/CTPN/src
ENV PYTHONPATH=$PYCAFFE_ROOT:$CTPN_ROOT:$PYTHONPATH
ENV PATH=$APP_ROOT/CTPN/caffe/build/tools:$PYCAFFE_ROOT:$PATH
RUN echo "$APP_ROOT/CTPN/caffe/build/lib" >> /etc/ld.so.conf.d/caffe.conf && ldconfig

# Config CRNN
WORKDIR $APP_ROOT/
RUN thrift -r -gen py -out gen_thrift interface.thrift

CMD cd CTPN && make caffe && echo "$APP_ROOT/CTPN/caffe/build/lib" >> /etc/ld.so.conf.d/caffe.conf && ldconfig && \
    cd .. && python server_thrift.py
```

I do not know whether there is any other better solution for this. And this is not a Nvidia-docker problem, right?

Thanks for reading and I will be waiting for your reply

**Comment by flx42** [comment]
The solution is specific to caffe, luckily for you I have an example here:
https://github.com/NVIDIA/gpu-rest-engine/blob/master/Dockerfile.caffe_server#L47

**Comment by luvvien** [comment]
> The solution is specific to caffe, luckily for you I have an example here:
> https://github.com/NVIDIA/gpu-rest-engine/blob/master/Dockerfile.caffe_server#L47



> I was compiling my project based on sceneReco , which is based on Caffe by Dockerfile. And I had successfully build the image and started the container. Everything seemed to be OK...but when I tryed to use my project to recognize a image, I got the following Message, and the container exited:
> 
> ```shell
> Check failed: error == cudaSuccess (8 vs. 0) no kernel image is available for execution on the device
> ```
> 
> Then when I checked the compiling logs, I found the message. My GPU model is GTX1080Ti, and the GPU arch(s) should be sm_61:
> 
> ```shell
> ...
> -- CUDA detected: 8.0
> -- Found cuDNN (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
> -- Automatic GPU detection failed. Building for all known architectures.
> -- Added CUDA NVCC flags for: sm_20 sm_21 sm_30 sm_35 sm_50
> -- OpenCV found (/usr/share/OpenCV)
> ...
> -- ******************* Caffe Configuration Summary *******************
> ...
> --
> -- NVIDIA CUDA:
> --   Target GPU(s)     :   Auto
> --   GPU arch(s)       :   sm_20 sm_21 sm_30 sm_35 sm_50
> --   cuDNN             :   Yes
> ...
> ```
> 
> Then I searched Google for this, and I found the issue #597, which like the similar problem I met. Then I tryed the solution, but Unfortunately, I got the following message:
> 
> ```shell
> CMake Warning:
>   Manually-specified variables were not used by the project:
>     CUDA_ARCH_BIN
> ```
> 
> And the following Error, then project exit when I tryed to recognize a image again:
> 
> ```shell
> Check failed: error == cudaSuccess (8 vs. 0) no kernel image is available for execution on the device
> ```
> 
> And the compiling logs:
> 
> ```shell
> ...
> -- Added CUDA NVCC flags for: sm_20 sm_21 sm_30 sm_35 sm_50
> ...
> --   GPU arch(s)       :   sm_20 sm_21 sm_30 sm_35 sm_50
> ...
> ```
> 
> Then I tryed to build the image Step-by-Step interactively inside the container. You guess what? I got the following message:
> 
> ```shell
> ...
> -- Added CUDA NVCC flags for: sm_61
> ...
> --   GPU arch(s)       :   sm_61
> ...
> ```
> 
> I was surprised and I immediately start my project and the program run well ! But I still have to build my project by the Dockerfile without entering the container then build myself. Uhh...I guess maybe the intermediate container created while building a image did not have a suitable Cuda environment ?
> 
> Ok. I try the following steps, and it works:
> 
> 1. not build caffe while building the images
> 2. build caffe in Dockerfile's `CMD` command
> 
> So Here is the old Dockerfile:
> 
> ```dockerfile
> FROM nvidia/cuda:8.0-devel-ubuntu16.04
> MAINTAINER Max <***>
> 
> 
> ENV TZ=Asia/Shanghai
> ENV APP_ROOT=/opt/code
> 
> RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
> WORKDIR $APP_ROOT/
> 
> RUN apt-get update && apt-get install -y --no-install-recommends \
>         build-essential \
>         cmake \
>         git \
>         wget \
>         zip \
>         unzip \
>         libatlas-base-dev \
>         libboost-all-dev \
>         libgflags-dev \
>         libgoogle-glog-dev \
>         libhdf5-serial-dev \
>         libleveldb-dev \
>         liblmdb-dev \
>         libopencv-dev \
>         libprotobuf-dev \
>         libsnappy-dev \
>         protobuf-compiler \
>         python-dev \
>         python-numpy \
>         python-setuptools \
>         python-scipy \
>         python-pip \
>         thrift-compiler \
>         vim && \
>     rm -rf /var/lib/apt/lists/*
> ADD dependency/pip-10.0.1.tar /
> RUN cd /pip-10.0.1 && python setup.py install && cd .. && rm -r pip-10.0.1
> # Only the v3.0.8 is the filtable version
> ADD dependency/cudnn-7.0-linux-x64-v3.0.8-prod.tar /
> RUN cp -P /cuda/include/cudnn.h /usr/include/
> RUN cp -P /cuda/lib64/libcudnn* /usr/lib/x86_64-linux-gnu/ && rm -r /cuda
> # Optional
> RUN git clone --depth=1 https://gitee.com/Nvidia/nccl.git
> RUN cd nccl && make -j"$(nproc)" install && cd .. && rm -rf nccl
> # Python dependency
> COPY requirements.txt $APP_ROOT/
> RUN pip install --no-cache-dir --trusted-host mirrors.aliyun.com -i http://mirrors.aliyun.com/pypi/simple/ -q -r requirements.txt
> 
> COPY . $APP_ROOT/
> RUN find . -name "*.pyc" -delete
> 
> # Config CTPN
> WORKDIR $APP_ROOT/CTPN/
> RUN cd caffe && cp Makefile.config.example Makefile.config && mkdir build
> RUN make caffe
> 
> # Set the environment variables so that the paths are correctly configured
> ENV PYCAFFE_ROOT=$APP_ROOT/CTPN/caffe/python
> ENV CTPN_ROOT=$APP_ROOT/CTPN/src
> ENV PYTHONPATH=$PYCAFFE_ROOT:$CTPN_ROOT:$PYTHONPATH
> ENV PATH=$APP_ROOT/CTPN/caffe/build/tools:$PYCAFFE_ROOT:$PATH
> RUN echo "$APP_ROOT/CTPN/caffe/build/lib" >> /etc/ld.so.conf.d/caffe.conf && ldconfig
> 
> # Config CRNN
> WORKDIR $APP_ROOT/
> RUN thrift -r -gen py -out gen_thrift interface.thrift
> 
> CMD python server_thrift.py
> ```
> 
> And the new Dockerfile:
> 
> ```dockerfile
> FROM nvidia/cuda:8.0-devel-ubuntu16.04
> MAINTAINER Max <***>
> 
> ENV TZ=Asia/Shanghai
> ENV APP_ROOT=/opt/code
> 
> RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
> WORKDIR $APP_ROOT/
> 
> RUN apt-get update && apt-get install -y --no-install-recommends \
>         build-essential \
>         cmake \
>         git \
>         wget \
>         zip \
>         unzip \
>         libatlas-base-dev \
>         libboost-all-dev \
>         libgflags-dev \
>         libgoogle-glog-dev \
>         libhdf5-serial-dev \
>         libleveldb-dev \
>         liblmdb-dev \
>         libopencv-dev \
>         libprotobuf-dev \
>         libsnappy-dev \
>         protobuf-compiler \
>         python-dev \
>         python-numpy \
>         python-setuptools \
>         python-scipy \
>         python-pip \
>         thrift-compiler \
>         vim && \
>     rm -rf /var/lib/apt/lists/*
> ADD dependency/pip-10.0.1.tar /
> RUN cd /pip-10.0.1 && python setup.py install && cd .. && rm -r pip-10.0.1
> # Only the v3.0.8 is the filtable version
> ADD dependency/cudnn-7.0-linux-x64-v3.0.8-prod.tar /
> RUN cp -P /cuda/include/cudnn.h /usr/include/
> RUN cp -P /cuda/lib64/libcudnn* /usr/lib/x86_64-linux-gnu/ && rm -r /cuda
> # Optional
> RUN git clone --depth=1 https://gitee.com/Nvidia/nccl.git
> RUN cd nccl && make -j"$(nproc)" install && cd .. && rm -rf nccl
> # Python dependency
> COPY requirements.txt $APP_ROOT/
> RUN pip install --no-cache-dir --trusted-host mirrors.aliyun.com -i http://mirrors.aliyun.com/pypi/simple/ -q -r requirements.txt
> 
> COPY . $APP_ROOT/
> RUN find . -name "*.pyc" -delete
> 
> # Config CTPN
> WORKDIR $APP_ROOT/CTPN/
> RUN cd caffe && cp Makefile.config.example Makefile.config && mkdir build
> #RUN make caffe
> 
> # Set the environment variables so that the paths are correctly configured
> ENV PYCAFFE_ROOT=$APP_ROOT/CTPN/caffe/python
> ENV CTPN_ROOT=$APP_ROOT/CTPN/src
> ENV PYTHONPATH=$PYCAFFE_ROOT:$CTPN_ROOT:$PYTHONPATH
> ENV PATH=$APP_ROOT/CTPN/caffe/build/tools:$PYCAFFE_ROOT:$PATH
> RUN echo "$APP_ROOT/CTPN/caffe/build/lib" >> /etc/ld.so.conf.d/caffe.conf && ldconfig
> 
> # Config CRNN
> WORKDIR $APP_ROOT/
> RUN thrift -r -gen py -out gen_thrift interface.thrift
> 
> CMD cd CTPN && make caffe && echo "$APP_ROOT/CTPN/caffe/build/lib" >> /etc/ld.so.conf.d/caffe.conf && ldconfig && \
>     cd .. && python server_thrift.py
> ```
> 
> I do not know whether there is any other better solution for this. And this is not a Nvidia-docker problem, right?
> 
> Thanks for reading and I will be waiting for your reply

I solved the problem through modify Cuda.cmake:

```
set(Caffe_known_gpu_archs "30 35 50 52 60 61 75")
```

I just add 75 for my rtx2060. Hope to help u.

**Comment by sarath0993** [comment]
Replacing lines in **Cuda.cmake** works for me in RTX 2080 Ti with Cuda 8.0

```
elseif(${CUDA_ARCH_NAME} STREQUAL "Auto")
caffe2_detect_installed_gpus(__cuda_arch_bin)
```

to

```
elseif(${CUDA_ARCH_NAME} STREQUAL "Auto")
set(__cuda_arch_bin "61")
```
