### ISSUE TITLE
nvidia-docker fails with latest drivers 396.45

### ISSUE THREAD

**Issue by jimfcarroll** [NVIDIA/nvidia-docker#802]
### 1. Issue or feature description

I had nvidia-docker working fine with cuda 9.2 on Ubuntu 18.04. I ran an `apt upgrade` which updated my driver to 396.45. The nvidia docker runtime now fails. See below.

### 2. Steps to reproduce the issue

install 396.45 and run `docker run --runtime=nvidia -it nvidia/cuda:9.2-cudnn7-runtime-ubuntu18.04` and it fails to start with:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.2 --pid=23692 /var/lib/docker/overlay2/591e2a8d62573d6e020c3ecde26cad75022d92a2fdecbb1860dacabc85b2c937/merged]\\\\nnvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown.
```

I also tried on a server I have with 16.04, which also has the latest driver at 396.45

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`

Ran on both 18.04 and 16.04. Same result.

 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by jimfcarroll** [comment]
It appears that doing the upgrade was the problem. I didn't realize the cuda installs it's own specific version of the nvidia driver (the latest version bundled in the cudaxxx.sh installer appears to be 396.37). I'll reinstall cuda and see if the problem persists.

**Comment by Tutotu** [comment]
i have the same problem.my nvidia dirver is 396.26 ,OS centos 7.4.but another nvidia driver no thie question。

 Error: failed to start container "video-definition-validator-oversea-bjpg-0": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=GPU-d376d3a0-fc65-72f4-de85-7062ff5c7e7b --compute --utility --require=cuda>=8.0 --pid=25308 /media/disk1/docker/overlay2/f5225fcac23dde6a4ec1d35c8a71919d6a686bce40854507572367587b1478c5/merged]\\\\nnvidia-container-cli: detection error: elf file read error: /usr/lib64/libnvidia-ptxjitcompiler.so.396.26\\\\n\\\"\"": unknown

**Comment by jimfcarroll** [comment]
I got this working by uninstalling everything. I needed to strip out all of cuda and ALL of nvidia-docker(2). The instructions in the README didn't delete ALL of nvidia-docker as it left several nvidia-container related packages. I also did a `sudo apt-get purge libnividia-container-tools` which (I think) is a base package for all of the nvidia-docker functionality. Then:

1. On my development machine running 18.04 I :
  1. removed cuda.
  1. installed the latest (396.45) nvidia driver.
  1. installed cuda 9.2 using the runner AND SKIPPED installing the driver
  1. installed nvidia-docker2

1. On my server (runtime) running 16.04 I :
  1. removed cuda
  1. installed the latest driver
  1. installed nvidia-docker2

**Comment by jimfcarroll** [comment]
Since I got this working, and you can find how above, I'm going to close this issue.

**Comment by NyanCatTW1** [comment]
For the record, I worked around this issue by compiling NVIDIA/libnvidia-container manually and removing libvdpau_nvidia.so from the video_libs array in srv/nvc_info.c
