### ISSUE TITLE
Error on "docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi"

### ISSUE THREAD

**Issue by NooneBug** [NVIDIA/nvidia-docker#832]
Hi all, 

when i try to run the command "docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi" the terminal returns me this error:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=11971 /var/lib/docker/overlay2/a8588e5d4ca0512d16f45c7052fdfe1743dbdef5fedde53cc1f203a7e27cf0e5/merged]\\\\nnvidia-container-cli: initialization error: cuda error: unknown error\\\\n\\\"\"": unknown.

can someone help me?

**Comment by flx42** [comment]
@NooneBug your driver installation is probably busted. You can try to launch a CUDA application outside of containers, like the CUDA samples, and it will probably fail too.
If that's the case, you need to fix your driver installation first.

**Comment by david-waterworth** [comment]
I'm seeing the same thing, I've installed the nvidia-driver package and they "work" in the sense that the full resolution of my monitor is now supported. Do you have a link which explains how to properly install the nvidia drivers in order to support nvidia-docker?

**Comment by flx42** [comment]
@david-waterworth `nvidia-docker` is compatible with 390.
You should install the `cuda-10-0` package instead.

**Comment by EthonDeep** [comment]
Hi  @flx42 :         
     i run the command   run_alignment_tool     .    something wrong ,Can you give me some advise?
root@1e9158ee6150:~/labelfusion/data/logs# run_alignment_tool 
Opening object alignment tool...
log folder: /root/labelfusion/data/logs
Traceback (most recent call last):
  File "/root/labelfusion/scripts/labelFusionApp.py", line 79, in <module>
    globalsDict=globals())
  File "/root/labelfusion/modules/labelfusion/setup.py", line 38, in setupLabelFusionDirector
    firstFrameToWorldTransform = utils.getFirstFrameToWorldTransform(filenames['transforms'])
TypeError: 'NoneType' object has no attribute '__getitem__'
Done.

**Comment by david-waterworth** [comment]
@flx42 I'm on debian and 384.130 is actually the latest driver in stable. So I assume installing nvidia-cuda-toolkit configured/installed something which installing nvidia-driver didn't.

I was under the impression that nvidia-docker only required the driver, is this not the case and is cuda also a requirement?

**Comment by flx42** [comment]
@david-waterworth you need the driver, but the `cuda-10-0` meta-package is a good start on Ubuntu. That's why I mentioned it.

You need `libcuda.so.1`, which is shipped with the driver. Not sure which package will provide this with your method.

**Comment by yylin1** [comment]
Hi , I have the same problem with nvidia-docker run command .

Env list:
- 16.04.1-Ubuntu SMP
- NVIDIA Docker version : v2.0.3
- Docker version : 18.03.0-ce
- GPU : GTX 1060 6G

```
$ nvidia-smi 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:03:00.0  On |                  N/A |
| 38%   29C    P8     6W / 120W |     62MiB /  6077MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1210      G   /usr/lib/xorg/Xorg                            59MiB |
+-----------------------------------------------------------------------------+
```
But when I run `nvidia-docker run ` always have OCI runtime problem.

- nvidia/cuda:10.0-base

```
$ docker run --runtime=nvidia --rm nvidia/cuda:10.0-base nvidia-smi 

ocker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 127, stdout: , stderr: exec command: [/usr/local/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=2606 /var/lib/docker/overlay2/cd031edc93494e3db83c5ae59ad32710c5d79e456e8bb4cb7e580e2074b7c1bf/merged]\\\\n/usr/local/bin/nvidia-container-cli: error while loading shared libraries: libnvidia-container.so.1: cannot open shared object file: No such file or directory\\\\n\\\"\"": unknown.
```

- nvidia/cuda:9.0-base

```
$ nvidia-docker run --rm nvidia/cuda:9.0-base nvidia-smi

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 127, stdout: , stderr: exec command: [/usr/local/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=4240 /var/lib/docker/overlay2/cd35edab02b25ef05ddf8ffaf87a884315508f28abf0fc459796c4101b4b3732/merged]\\\\n/usr/local/bin/nvidia-container-cli: error while loading shared libraries: libnvidia-container.so.1: cannot open shared object file: No such file or directory\\\\n\\\"\"": unknown.
```

This problem is always after I install the environment for a while. On the next day, the nvidia-docker run will appear again.

**Comment by yylin1** [comment]
I find `issues` maybe deploy problem ? 
https://github.com/NVIDIA/nvidia-docker/issues/835#issuecomment-427434729

To Update `libnvidia-container`?
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.0.0

**Comment by RenaudWasTaken** [comment]
Hello yylin1 can you open a separate issue, you are facing a different issue.
Also if the problem is periodically reappearing it is likely someone or something outside of nvidia-docker is changing your environment.

Closing as the original issue was solved.

**Comment by fardok** [comment]
hi  everyone!

i solved that error

docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-sm

error is because librarys dont connect to right place
theres two ways to fix that:

1) docker run --runtime=nvidia --rm nvidia/cuda:9.0-base  bash
inside container write:  **ldconfig**
then for check that is all ok write  **nvidia-smi**  
then in another console write:  **docker ps** and find your container
then save them to disk:  **docker commit c3f279d17e0a  newname/newname:fixed**
instead of  c3f279d17e0a  write  container id from docker ps
thats all

2) **docker run --runtime=nvidia --rm nvidia/cuda:9.0-base _ldconfig_ ;nvidia-smi**
                                                                                              ^^^^^^^^^^ ldconfig; nvidia-smi


thats all

**Comment by fardok** [comment]
theres another errors inside  nvidia/cuda  and  tensorflow/tensorflow

**Comment by fardok** [comment]
for example 
docker run --runtime=nvidia -it --rm -p 90:8080 -v /home/fardok/test:/tmp **-v /usr/local/lib:/usr/local/lib** tensorflow/tensorflow:latest-gpu bash


-v /usr/local/lib:/usr/local/lib   -in  /usr/local/lib you need put tensorflow libs that support GPU. its important!  becouse tensorflow have version only for CPU
 
 -v /home/fardok/test:/tmp     -here we  mount our host folder /home/fardok/test  to  container folder /tmp


when you inside container you also need write command  **ldconfig**  for link tensoflow libs

**Comment by RenaudWasTaken** [comment]
Hello!

@fardok you seem to have a different issue...
You shouldn't be regenerating your ldcache inside your container as this is part of the operations we are executing.

**Comment by fardok** [comment]
for example 
docker run --runtime=nvidia -it --rm -p 90:8080 -v /home/fardok/test:/tmp **-v /usr/local/lib:/usr/local/lib** tensorflow/tensorflow:latest-gpu bash


-v /usr/local/lib:/usr/local/lib   -in  /usr/local/lib you need put tensorflow libs that support GPU. its important!  becouse tensorflow have version only for CPU
 
 -v /home/fardok/test:/tmp     -here we  mount our host folder /home/fardok/test  to  container folder /tmp


when you inside container you also need write command  ldconfig  for link tensoflow libs

**Comment by chossimbaone** [comment]
Hi. I do not know if this goes for none DGX-users but i just fixed the problem by starting nv-hostengine which has crashed on one of our servers. If so try the command below:
 sudo /usr/bin/nv-hostengine
