### ISSUE TITLE
Unable to find the GPU using Theano

### ISSUE THREAD

**Issue by tboquet** [NVIDIA/nvidia-docker#95]
I just installed the latest version of nvidia-docker and GPUs aren't detected:

```python
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: Unable to get the number of gpus available: no CUDA-capable device is detected)
```

I tested to install Theano (the past 4 releases and the latest master) in the official TensorFlow image and using a [clean image](https://hub.docker.com/r/tboquet/anacuthe7hc4/~/dockerfile/):

```shell
NV_GPU=0 nvidia-docker run -ti --rm gcr.io/tensorflow/tensorflow:latest-devel-gpu
```

```shell
 NV_GPU=0 nvidia-docker run -ti --rm tboquet/anacuthe7hc4
```

I'm not sure if I have to do something different.
I can run `nvidia-smi` in both containers and Tensorflow examples without problems.

**Comment by flx42** [comment]
Does `nvidia-docker run --rm nvidia/cuda nvidia-smi` works?

**Comment by tboquet** [comment]
I just updated my comment!

**Comment by tboquet** [comment]
Mm ok I think I have it. It's not working on Tensorflow either. It has to be the installation of new drivers:
```python
E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:229] kernel version 361.42 does not match DSO version 352.79 -- cannot find working devices in this configuration
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.
```

**Comment by flx42** [comment]
Thanks for the bug report, we will see if there is a way to prevent this from happening in the future.

**Comment by tboquet** [comment]
Ok I resolved the driver installation problem like this:

- Find libcuda packages installed
```shell
dpkg -l | grep libcuda
```
- Uninstall the old package
```shell
sudo dpkg --purge libcuda1-352
```
- check for the latest version
```shell
sudo locate libcuda
```
- reinstall it
```shell
sudo dpkg -i /var/cache/apt/archives/libcuda1-361_361.42-0ubuntu0~gpu14.04.1_amd64.deb
```

- reinstall `nvidia-docker` and recreate the volume

```shell
# Install nvidia-docker and nvidia-docker-plugin
wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc/nvidia-docker_1.0.0.rc_amd64.tar.xz
sudo tar --strip-components=1 -C /usr/bin -xvf /tmp/nvidia-docker_1.0.0.rc_amd64.tar.xz && rm /tmp/nvidia-docker*.tar.xz

# One-time setup
sudo nvidia-docker volume setup
```

**Comment by flx42** [comment]
You should be using the plugin instead, if that works for you:
https://github.com/nvidia/nvidia-docker#plugin-install-recommended
https://github.com/NVIDIA/nvidia-docker/wiki/Using-nvidia-docker-plugin
It should be more robust with the plugin.
